if (typeof spider === 'undefined') { var spider = {}; }
spider.windowTheme = "flat";
spider.gadgetTheme = "flat";
var _S2="Window 1";
var _S3="Window 2";
var _S1="Window 0 - Resizable";
if("undefined"==typeof Spider)var Spider={};spider.systembase={localFiles:null,getLocalFile:function(a){for(var b=0;b<this.localFiles.length;b++)if(this.localFiles[b].name===a)return this.localFiles[b];return null}};function spider_BankerRound(a){return 0>a?Math.ceil(a-0.5):Math.floor(a+0.5)}function spider_CastByte(a){a&=255;return 127<a?-(256-a):a}function spider_CastCharacter(a){return a&65535}function spider_CastAscii(a){return a&255}function spider_CastUnicode(a){return a&65535}
function spider_CastWord(a){a&=65535;return 32767<a?-(65536-a):a}function spider_CastLong(a){a&=4294967295;return 2147483647<a?-(4294967296-a):a}function spider_CastQuad(a){return 0<=a?Math.floor(a):Math.ceil(a)}function spider_XOr(a,b){return(a||b)&&!(a&&b)}function spider_AssignFixedString(a,b){return b<a.length?a.substring(0,b):a}function spider_SysArray(){this.structure=null;this.nbDimensions=0;this.type=this.dimensions=null}
function spider_SysList(){this.type=this.current=this.last=this.first=null;this.index=0;this.isIndexInvalid=!1;this.field="";this.nbElements=0;this.isNative=!1}function spider_SysMap(){this.map={};this.current=null;this.currentIndex=-1;this.type=this.keys=this.currentKey=null;this.isNative=!1};

if("undefined"===typeof spider)var spider={};
spider.object=function(c){return{map:{},dynamicCounter:1E5,Allocate:function(a){var b={};-1==a?(b.id=this.dynamicCounter,b.resultId=b.id,this.dynamicCounter++):(c&&c(a),b.id=a,b.resultId=1);return this.map[b.id]=b},Get:function(a){return this.map.hasOwnProperty(a)?this.map[a]:null},Remove:function(a){delete this.map[a]},EnumerateAll:function(a){for(var b in this.map)a(b)},CleanAll:function(){for(var a in this.map)c&&c(a)},Is:function(a){return this.map.hasOwnProperty(a)?1:0}}};

function spider_InitMap(){}function spider_NewMap(a,b){var c=new spider_SysMap;c.type=a;c.isNative=b;return c}function spider_GetMapElement(a,b){return a.map.hasOwnProperty(b)?a.map[b]:0}function spider_CreateMapElement(a,b){return a.map.hasOwnProperty(b)?a.map[b]:(a.current=new a.type,a.currentKey=b,a.map[b]=a.current)}function spider_AddMapElement(a,b){a.current=new a.type;a.currentKey=b;return a.map[b]=a.current}
function spider_ResetMap(a){a.keys=Object.keys(a.map);a.currentIndex=-1;a.currentKey=null}function spider_NextMapElement(a){a.currentIndex<a.keys.length-1?(a.currentIndex++,a.currentKey=a.keys[a.currentIndex],a.current=a.map[a.currentKey]):(a.currentIndex=-1,a.current=null,a.currentKey=null);return a.current}function spider_MapKey(a){return a.currentKey?a.currentKey:""}function spider_MapSize(a){return Object.keys(a.map).length}
function spider_DeleteMapElement(a,b){"undefined"===typeof b?a.currentKey&&delete a.map[a.currentKey]:a.map.hasOwnProperty(b)&&delete a.map[b]}function spider_FindMapElement(a,b){return a.map.hasOwnProperty(b)?(a.current=a.map[b],a.currentKey=b,a.current):0}function spider_CopyMap(a,b){var c=Object.keys(a.map);b.map={};for(var d=0;d<c.length;d++){var e=c[d],f=new a.type;a.map[e].copy(f);b.map[e]=f}b.currentIndex=-1;b.current=null;b.currentKey=null}function spider_ClearMap(a){a.map={}}
function spider_FreeMap(a){spider.ClearMap(a)}function spider_PushMapPosition(a){a.stack||(a.stack=[]);a.stack.push(a.currentIndex)}function spider_PopMapPosition(a){a.stack&&0<a.stack.length&&(a.currentIndex=a.stack.pop(),a.keys=Object.keys(a.map))};

if("undefined"===typeof spider)var spider={};function spider_Event_Init(){}
spider.event={map:{},eventWindow:0,eventObject:0,eventType:0,eventData:null,MakeKey:function(a,c,b,d){return a.toString()+"_"+c.toString()+"_"+b.toString()+"_"+d.toString()},SendGeneric:function(a,c,b,d){a=spider.event.MakeKey(a,c,b,d);if(a=spider.event.map[a])for(var e in a)a[e]()},SendLoading:function(a,c,b,d){a=spider.event.MakeKey(a,-1,-1,-1);if(a=spider.event.map[a])for(var e in a)a[e](c,b,d)},Send:function(a,c,b,d){this.eventWindow=c;this.eventObject=b;this.eventType=d;this.SendGeneric(a,c,
b,d);this.SendGeneric(a,c,b,-1);this.SendGeneric(a,c,-1,-1);this.SendGeneric(a,-1,-1,-1)}};function spider_BindEvent(a,c,b,d,e){"undefined"===typeof b&&(b=-1);"undefined"===typeof d&&(d=-1);"undefined"===typeof e&&(e=-1);a=spider.event.MakeKey(a,b,d,e);spider.event.map[a]||(spider.event.map[a]={});spider.event.map[a][c]=c}
function spider_UnbindEvent(a,c,b,d,e){"undefined"===typeof b&&(b=-1);"undefined"===typeof d&&(d=-1);"undefined"===typeof e&&(e=-1);a=spider.event.MakeKey(a,b,d,e);if(a=spider.event.map[a])for(var f in a)f==c&&delete a[c]}function spider_EventWindow(){return spider.event.eventWindow}function spider_EventMenu(){return spider.event.eventObject}function spider_EventGadget(){return spider.event.eventObject}function spider_EventTimer(){return spider.event.eventObject}
function spider_EventType(){return spider.event.eventType}function spider_EventData(){return spider.event.eventData};

if("undefined"==typeof Spider)var Spider={};function spider_ElapsedMilliseconds(){return(new Date).getTime()};

if("undefined"==typeof Spider)var Spider={};function spider_Asc(a){return""===a?0:a.charCodeAt(0)}function spider_Bin(a,b){"undefined"===typeof b&&(b=13);switch(b){case 1:case 24:a&=255;break;case 3:case 25:a&=65535;break;case 5:return spider_Right(a.toString(2),32)}return a.toString(2)}function spider_Chr(a){return String.fromCharCode(a)}function spider_LCase(a){return a.toLowerCase()}function spider_UCase(a){return a.toUpperCase()}
function spider_CountString(a,b){if(0>=b.length)return a.length+1;for(var c=0,d=0,e=b.length;;)if(d=a.indexOf(b,d),0<=d)c++,d+=e;else break;return c}function spider_FindString(a,b,c,d){"undefined"===typeof c&&(c=1);"undefined"===typeof d&&(d=0);return a&&b&&""!==a&&""!==b?0===d?a.indexOf(b,c-1)+1:a.toUpperCase().indexOf(b.toUpperCase(),c-1)+1:0}function spider_InsertString(a,b,c){1>c?c=1:c>a.length+1&&(c=a.length+1);return a.substr(0,c-1)+b+a.substr(c-1)}
function spider_Space(a){if(0>=a)return"";for(var b=a/2,c=" ";c.length<=b;)c+=c;return c+c.substring(0,a-c.length)}function spider_Str(a){return""+a}function spider_StrD(a,b){var c;c="undefined"===typeof b?a.toString():a.toFixed(b);"Infinity"==c&&(c="+Infinity");return c}function spider_StrF(a,b){return spider_StrD(a,b)}function spider_StrU(a,b){"undefined"===typeof b&&(b=13);switch(b){case 1:case 24:a&=255;break;case 3:case 25:a&=65535}return a.toString(10)}
function spider_Val(a){for(var b=0,c=a.length-1,d=0;d<=c&&(" "==a.charAt(d)||"t"==a.charAt(d));)d++;c=a.charAt(d);"-"==c&&(d++,b=1,c=a.charAt(d));a="%"==c?parseInt(spider_Right(a,a.length-d-1),2):"$"==c?parseInt(spider_Right(a,a.length-d-1),16):parseInt(spider_Right(a,a.length-d),10);isNaN(a)&&(a=0);return b?-a:a}function spider_ValF(a){return parseFloat(a,10)}function spider_ValD(a){return parseFloat(a,10)}function spider_Right(a,b){var c=a.length;return a.substring(c-b,c)}
function spider_Left(a,b){return a.substring(0,b)}function spider_Mid(a,b,c){"undefined"===typeof c&&(c=a.length);1>b&&(b=1);return a.substring(b-1,b+c-1)}function spider_LTrim(a,b){"undefined"===typeof b&&(b=" ");for(var c=0,d=a.length-1;c<=d&&a.charAt(c)==b;)c++;return a.substr(c)}function spider_RTrim(a,b){"undefined"===typeof b&&(b=" ");for(var c=a.length-1;0<c&&a.charAt(c)==b;)c--;return a.substr(0,c-0+1)}
function spider_Trim(a,b){"undefined"===typeof b&&(b=" ");for(var c=0,d=a.length-1;c<=d&&a.charAt(c)==b;)c++;for(;d>c&&a.charAt(d)==b;)d--;return a.substr(c,d-c+1)}function spider_Len(a){return a.length}function spider_Hex(a,b){"undefined"===typeof b&&(b=13);switch(b){case 1:case 24:a&=255;break;case 3:case 25:a&=65535;break;case 5:a&=4294967295}return a.toString(16).toUpperCase()}
function spider_ReplaceString(a,b,c,d,e,f){"undefined"===typeof d&&(d=0);"undefined"===typeof e&&(e=1);"undefined"===typeof f&&(f=-1);if(a&&b)for(e-=1,1==d&&(b=b.toUpperCase());f;){e=1==d?a.toUpperCase().indexOf(b,e):a.indexOf(b,e);if(-1==e)break;a=a.substring(0,e)+c+a.substring(e+b.length);e+=c.length;f--}return a}function spider_RemoveString(a,b,c,d,e){return spider_ReplaceString(a,b,"",c,d,e)}function spider_ReverseString(a){var b="",c;for(c=a.length-1;0<=c;c--)b+=a.charAt(c);return b}
function spider_RSet(a,b,c){"undefined"===typeof c&&(c=" ");var d=b-a.length;if(a.length>b)return a.substring(0,b);if(0<d){b=c;for(d--;d;)d--,b+=c;return b+a}return a}function spider_LSet(a,b,c){"undefined"===typeof c&&(c=" ");var d=b-a.length;if(a.length>b)return a.substring(0,b);if(0<d){b=c;for(d--;d;)d--,b+=c;return a+b}return a}function spider_StringField(a,b,c){return""===c?a:1<=b&&(a=a.split(c),a.length>=b)?a[b-1]:""};

function spider_Date(a,e,b,d,k,f){if("undefined"===typeof a)return a=new XDate,a.getTime()/1E3-60*a.getTimezoneOffset();a=new XDate(a,e-1,b,d,k,f,!0);return a.getTime()/1E3}function spider_Year(a){return-1==a?0:(new XDate(1E3*a,!0)).getFullYear()}function spider_Month(a){return-1==a?0:(new XDate(1E3*a,!0)).getMonth()+1}function spider_Day(a){return-1==a?0:(new XDate(1E3*a,!0)).getDate()}function spider_DayOfWeek(a){return-1==a?0:(new XDate(1E3*a,!0)).getDay()}
function spider_DayOfYear(a){if(-1==a)return 0;a=new XDate(1E3*a,!0);for(var e=0,b=a.getFullYear(),d=0;d<a.getMonth();d++)e+=XDate.getDaysInMonth(b,d);return e+=a.getDate()}function spider_Hour(a){return-1==a?0:(new XDate(1E3*a,!0)).getHours()}function spider_Minute(a){return-1==a?0:(new XDate(1E3*a,!0)).getMinutes()}function spider_Second(a){return-1==a?0:(new XDate(1E3*a,!0)).getSeconds()}
function spider_AddDate(a,e,b){a=new XDate(1E3*a,!0);switch(e){case 0:a.addYears(b,!0);break;case 1:a.addMonths(b,!0);break;case 2:a.addWeeks(b);break;case 3:a.addDays(b);break;case 4:a.addHours(b);break;case 5:a.addMinutes(b);break;case 6:a.addSeconds(b)}return a.getTime()/1E3}
function spider_FormatDate(a,e){var b=new XDate(1E3*e,!0),d=spider_ReplaceString(a,"%yyyy",""+b.getFullYear()),d=spider_ReplaceString(d,"%yy",spider_Right(""+b.getFullYear(),2)),d=spider_ReplaceString(d,"%mm",spider_RSet(""+(b.getMonth()+1),2,"0")),d=spider_ReplaceString(d,"%dd",spider_RSet(""+b.getDate(),2,"0")),d=spider_ReplaceString(d,"%hh",spider_RSet(""+b.getHours(),2,"0")),d=spider_ReplaceString(d,"%ii",spider_RSet(""+b.getMinutes(),2,"0"));return d=spider_ReplaceString(d,"%ss",spider_RSet(""+
b.getSeconds(),2,"0"))}
function spider_ParseDate(a,e){var b=0,d,k,f=1970,l=1,m=1,n=0,p=0,q=0,g,h=function(a){for(g=0;$.isNumeric(a.charAt(g))&&g<a.length;)g++;return spider_Val(a)};if(a&&e){for(var c=0;c<a.length;)if(d=a.charAt(c),k=e.charAt(b),"%"==d)if(c++,"yyyy"==a.substring(c,c+4)){f=h(e.substring(b,b+4));if(-1==f)return-1;b+=g;c+=4}else if("yy"==a.substring(c,c+2)){f=h(e.substring(b,b+2));if(-1==f)return-1;f=70<=f?f+1900:f+2E3;b+=g;c+=2}else if("mm"==a.substring(c,c+2)){l=h(e.substring(b,b+2));if(-1==l)return-1;"0"==
k&&(b+=g);c+=2}else if("dd"==a.substring(c,c+2)){m=h(e.substring(b,b+2));if(-1==m)return-1;b+=g;c+=2}else if("hh"==a.substring(c,c+2)){n=h(e.substring(b,b+2));if(-1==n)return-1;b+=g;c+=2}else if("ii"==a.substring(c,c+2)){p=h(e.substring(b,b+2));if(-1==p)return-1;b+=g;c+=2}else if("ss"==a.substring(c,c+2)){q=h(e.substring(b,b+2));if(-1==q)return-1;b+=g;c+=2}else b++,c++;else{if(d!=k)return-1;c++;b++}if(b==e.length)return spider_Date(f,l,m,n,p,q)}return-1};

if("undefined"===typeof spider)var spider={};if("undefined"===typeof document)var document={};if("undefined"===typeof window)var window={};function spider_FinishDirectory(a){-1==a?spider.filesystem.objects.CleanAll():spider.filesystem.objects.Get(a)&&spider.filesystem.objects.Remove(a)}spider.filesystem={objects:new spider.object(spider_FinishDirectory),fs:null,cwd:null};function spider_RequestFileSystem(a,b,c){window.requestFileSystem=window.requestFileSystem||window.webkitRequestFileSystem}
function spider_ExamineDirectory(a,b,c,d){spider.filesystem.objects.Allocate(a)}function spider_GetExtensionPart(a){a=a.split(".");return 1===a.length||""===a[0]&&2===a.length?"":a.pop()};

if("undefined"===typeof spider)var spider={};function spider_PeekB(a,b){return a.view8[b]}function spider_PeekA(a,b){return a.viewu8[b]}function spider_PeekW(a,b){return a.view.getInt16(b,!0)}function spider_PeekU(a,b){return a.view.getUint16(b,!0)}function spider_PeekC(a,b){return a.view.getUint16(b,!0)}function spider_PeekL(a,b){return a.view.getInt32(b,!0)}function spider_PeekF(a,b){return a.view.getFloat32(b,!0)}function spider_PeekD(a,b){return a.view.getFloat64(b,!0)}var spider_Memory_CharacterReadOffset;
function spider_Memory_ReadUTF8Character(a,b){var c;c=a[b];return 0===(c&128)?(spider_Memory_CharacterReadOffset=1,c):192==(c&224)?(spider_Memory_CharacterReadOffset=2,(c&31)<<6|a[b+1]&63):224==(c&240)?(spider_Memory_CharacterReadOffset=3,(c&15)<<12|(a[b+1]&63)<<6|(a[b+2]&63)<<0):0}
function spider_Memory_ReadCharacter(a,b,c){switch(c){case 24:return spider_Memory_CharacterReadOffset=1,a[b];case 25:return spider_Memory_CharacterReadOffset=2,a[b]<<8|a[b+1];default:return spider_Memory_ReadUTF8Character(a,b)}}
function spider_PeekS(a,b,c,d){"undefined"===typeof d&&(d=2);"undefined"===typeof c&&(c=-1);d&=31;var e,f="";0===d&&(d=25);if(-1<=c)for(;c;){e=spider_Memory_ReadCharacter(a.viewu8,b,d);if(0===e)break;f+=String.fromCharCode(e);b+=spider_Memory_CharacterReadOffset;c--}return f}function spider_PokeB(a,b,c){a.view8[b]=c}function spider_PokeA(a,b,c){a.viewu8[b]=c}function spider_PokeW(a,b,c){a.view.setInt16(b,c,!0)}function spider_PokeU(a,b,c){a.view.setUint16(b,c,!0)}
function spider_PokeC(a,b,c){a.view.setUint16(b,c,!0)}function spider_PokeL(a,b,c){a.view.setInt32(b,c,!0)}function spider_PokeF(a,b,c){a.view.setFloat32(b,c,!0)}function spider_PokeD(a,b,c){a.view.setFloat64(b,c,!0)}function spider_Memory_WriteUTF8Character(a,b,c){return 128>c?(a[b]=c,1):2048>c?(a[b]=192|c>>6,a[b+1]=128|c&63,2):55296>c||57344<=c?(a[b]=224|c>>12,a[b+1]=128|c>>6&63,a[b+2]=128|c&63,3):0}
function spider_Memory_WriteCharacter(a,b,c,d){switch(d){case 24:return a[b]=c,1;case 25:return a[b]=c>>8,a[b+1]=c,2;default:return spider_Memory_WriteUTF8Character(a,b,c)}}function spider_PokeS(a,b,c,d,e){"undefined"===typeof e&&(e=2);"undefined"===typeof d&&(d=-1);var f=c.length;if(-1==d||d>f)d=f;var f=b,g=e&31;0===g&&(g=25);for(var h=0;h<d;h++)b+=spider_Memory_WriteCharacter(a.viewu8,b,c.charCodeAt(h),g);0===(e&256)&&(a.viewu8[b]=0,25==g&&(a.viewu8[b+1]=0));return b-f}
function spider_AllocateMemory(a,b){var c=new ArrayBuffer(a);c.view8=new Int8Array(c);c.viewu8=new Uint8Array(c);c.view=new DataView(c);return c}function spider_ReAllocateMemory(a,b,c){if(a){if(b==a.byteLength)return a;if(b<a.byteLength)return a.slice(0,b);b=spider_AllocateMemory(b,c);b.view8.set(a.view8,0,a.byteLength);return b}return spider_ReAllocateMemory(b,c)}function spider_FreeMemory(a){}
function spider_CompareMemory(a,b,c,d,e){a=new Int8Array(a,b,e);c=new Int8Array(c,d,e);for(d=0;d!=e;d++)if(a[d]!=c[d])return 0;return 1}function spider_MemorySize(a){return a.byteLength}function spider_AllocateStructure(a,b){return new a}function spider_FreeStructure(a){};

if("undefined"===typeof spider)var spider={};function spider_InitImageDecoder(){};

function spider_InitImage(){}function spider_FreeImage(a){-1==a?spider.image.objects.CleanAll():spider.image.objects.Get(a)&&spider.image.objects.Remove(a)}
spider.image={objects:new spider.object(spider_FreeImage),counter:0,GetCSS:function(a){if(!a)return null;a.spiderCounter||(this.counter++,a.spiderCounter=this.counter);var b="spiderimage_"+a.spiderCounter;if(!a.css){a.css=!0;var c={};c["."+b]={"background-image":"url("+a.toDataURL()+")","background-repeat":"no-repeat",width:""+a.width+"px",height:""+a.height+"px"};$.injectCSS(c)}return b},GetGrayedCSS:function(a){a.spiderCounter||(this.counter++,a.spiderCounter=this.counter);var b="spiderimagegrayed_"+
a.spiderCounter;if(!a.grayedCss){a.grayedCss=!0;var c={},d="."+b,e;e=document.createElement("canvas");var f=e.getContext("2d");e.width=a.width;e.height=a.height;f.drawImage(a,0,0);for(var g=f.getImageData(0,0,e.width,e.height),l=0;l<g.height;l++)for(var k=0;k<g.width;k++){var h=4*l*g.width+4*k,n=(g.data[h]+g.data[h+1]+g.data[h+2])/3;g.data[h]=n;g.data[h+1]=n;g.data[h+2]=n}f.putImageData(g,0,0,0,0,g.width,g.height);e=e.toDataURL();c[d]={"background-image":"url("+e+")","background-repeat":"no-repeat",
width:""+a.width+"px",height:""+a.height+"px"};$.injectCSS(c)}return b}};
function spider_LoadImage(a,b,c){"undefined"===typeof c&&(c=0);var d=spider.image.objects.Allocate(a),e=document.createElement("canvas");d.image=e;var f=new Image;$(f).on({load:function(){e.width=f.width;e.height=f.height;e.getContext("2d").drawImage(f,0,0);var a=spider_GetExtensionPart(b).toLowerCase();"jpg"==a||"jpeg"==a?d.originalFormat=1195724874:"png"==a?d.originalFormat=4673104:"bmp"==a&&(d.originalFormat=5262658);spider.event.SendLoading(18,1,b,d.id)},error:function(){spider.event.SendLoading(19,
1,b,d.id)}});c&65536?(a=spider.systembase.getLocalFile(b))?(c=new FileReader,$(c).on({load:function(a){f.src=a.target.result},error:function(){spider.event.SendLoading(19,1,b,d.id)}}),c.readAsDataURL(a)):spider.event.SendLoading(19,1,b,d.id):f.src=b;return d.resultId}
function spider_CopyImage(a,b){var c,d=spider.image.objects.Allocate(b);if(c=spider.image.objects.Get(a)){var e=document.createElement("canvas");e.width=c.image.width;e.height=c.image.height;d.image=e;e.getContext("2d").drawImage(c.image,0,0)}return d.resultId}
function spider_CreateImage(a,b,c,d,e){"undefined"===typeof e&&(e=0);a=spider.image.objects.Allocate(a);d=document.createElement("canvas");d.width=b;d.height=c;a.image=d;d=d.getContext("2d");-1==e?d.clearRect(0,0,b,c):(d.fillStyle=spider_helper_ColorToHtml(e),d.fillRect(0,0,b,c));return a.resultId}
function spider_GrabImage(a,b,c,d,e,f){b=spider.image.objects.Allocate(b);if(a=spider.image.objects.Get(a)){var g=document.createElement("canvas");g.width=e;g.height=f;b.image=g;g.getContext("2d").drawImage(a.image,c,d,e,f,0,0,e,f)}return b.resultId}function spider_ImageOutput(a){return(a=spider.image.objects.Get(a))?(a.image.css=!1,a.image.grayedCss=!1,{image:a,canvas:a.image,context:a.image.getContext("2d"),stopDrawingCallback:null}):null}
function spider_EncodeImage(a,b,c){"undefined"===typeof b&&(b=4673104);"undefined"===typeof c&&(c=7);var d;return(d=spider.image.objects.Get(a))?1195724874==b?d.image.toDataURL("image/jpeg",c/10):d.image.toDataURL("image/png"):""}function spider_ExportImage(a,b,c){"undefined"===typeof c&&(c=4673104);return(a=spider.image.objects.Get(a))?(a.image.toBlob(function(a){saveAs(a,b)},1195724874==c?"image/jpeg":"image/png"),1):0}function spider_ImageDepth(a){return spider.image.objects.Get(a)?32:0}
function spider_ImageFormat(a){var b;return(b=spider.image.objects.Get(a))?b.originalFormat?b.originalFormat:0:0}function spider_ImageWidth(a){var b;return(b=spider.image.objects.Get(a))?b.image.width:0}function spider_ImageHeight(a){var b;return(b=spider.image.objects.Get(a))?b.image.height:0}
function spider_ResizeImage(a,b,c,d){"undefined"===typeof d&&(d=0);if(a=spider.image.objects.Get(a)){var e=document.createElement("canvas");-65535==b&&(b=a.image.width);-65535==c&&(c=a.image.height);e.width=b;e.height=c;a.image.css=!1;a.image.grayedCss=!1;var f=e.getContext("2d");if(1==d)if(f.webkitImageSmoothingEnabled||f.mozImageSmoothingEnabled||f.imageSmoothingEnabled)f.webkitImageSmoothingEnabled=!1,f.mozImageSmoothingEnabled=!1,f.imageSmoothingEnabled=!1,f.drawImage(a.image,0,0,a.image.width,
a.image.height,0,0,b,c);else{var g=a.image.getContext("2d");d=a.image.width;for(var l=a.image.height,k=g.getImageData(0,0,d,l),g=f.createImageData(b,c),k=k.data,h=g.data,n=d/b,l=l/c,p=0;p<c;p++)for(var q=p*b,r=(p*l|0)*d,m=0;m<b;m++){var s=m*n|0;h[4*(q+m)+0]=k[4*(r+s)+0];h[4*(q+m)+1]=k[4*(r+s)+1];h[4*(q+m)+2]=k[4*(r+s)+2];h[4*(q+m)+3]=k[4*(r+s)+3]}f.putImageData(g,0,0)}else f.drawImage(a.image,0,0,a.image.width,a.image.height,0,0,b,c);a.image=e;return 1}return 0}
function spider_ImageID(a){var b;return(b=spider.image.objects.Get(a))?b.image:null}function spider_IsImage(a){return spider.image.objects.Is(a)};

function spider_Init2DDrawing(){}spider.drawing={output:null,context:null,frontColor:0,backColor:0,mode:0,stopDrawingCallback:null};function spider_helper_ColorToHtml(a){return"#"+spider_LSet((a&255).toString(16),2,"0")+spider_LSet((a>>8&255).toString(16),2,"0")+spider_LSet((a>>16&255).toString(16),2,"0")}
function spider_2ddrawing_getTextHeight(a){a=$("<span>Hg</span>").css("font",a);var c=$('<div style="display: inline-block; width: 1px; height: 0px;"></div>'),b=$("<div></div>");b.append(a,c);$("body").append(b);var d={};try{c.css({verticalAlign:"baseline"}),d.ascent=Math.ceil(c.offset().top-a.offset().top),c.css({verticalAlign:"bottom"}),d.height=Math.ceil(c.offset().top-a.offset().top),d.descent=Math.ceil(d.height-d.ascent)}finally{b.remove()}return d}
function spider_StartDrawing(a){spider.drawing.output=a;spider.drawing.context=a.context;spider.drawing.stopDrawingCallback=a.stopDrawingCallback;spider.drawing.frontColor=0;spider.drawing.backColor=16777215;spider.drawing.mode=0;spider.drawing.context.lineWidth=1;spider.drawing.context.font="12pt arial";return a.context}
function spider_Box(a,c,b,d,e){"undefined"===typeof e&&(e=spider.drawing.frontColor);var f=spider.drawing.context;4==spider.drawing.mode?(f.beginPath(),f.rect(a+0.5,c+0.5,b,d),f.strokeStyle=spider_helper_ColorToHtml(e),f.stroke()):(f.fillStyle=spider_helper_ColorToHtml(e),f.fillRect(a,c,b,d))}function spider_DrawAlphaImage(a,c,b,d){"undefined"===typeof d&&(d=255);var e=spider.drawing.context,f=e.globalAlpha;e.globalAlpha=d/255;e.drawImage(a,c,b);e.globalAlpha=f}
function spider_DrawImage(a,c,b,d,e){var f=spider.drawing.context;"undefined"===typeof d?f.drawImage(a,c,b):f.drawImage(a,0,0,a.width,a.height,c,b,d,e)}function spider_Plot(a,c,b){"undefined"===typeof b&&(b=spider.drawing.frontColor);var d=spider.drawing.context;d.fillStyle=spider_helper_ColorToHtml(b);d.fillRect(a,c,1,1)}function spider_Point(a,c){var b=spider.drawing.context.getImageData(a,c,1,1).data;return b[0]|b[1]<<8|b[2]<<16}function spider_OutputDepth(){return 32}
function spider_OutputWidth(){return spider.drawing.context.canvas.width}function spider_OutputHeight(){return spider.drawing.context.canvas.height}function spider_Line(a,c,b,d,e){"undefined"===typeof e&&(e=spider.drawing.frontColor);var f=spider.drawing.context;f.beginPath();f.moveTo(a,c);f.lineTo(a+b-1,c+d-1);f.strokeStyle=spider_helper_ColorToHtml(e);f.stroke()}
function spider_Line(a,c,b,d,e){"undefined"===typeof e&&(e=spider.drawing.frontColor);var f=spider.drawing.context;f.beginPath();f.moveTo(a,c);f.lineTo(a+b-1,c+d-1);f.strokeStyle=spider_helper_ColorToHtml(e);f.stroke()}function spider_LineXY(a,c,b,d,e){"undefined"===typeof e&&(e=spider.drawing.frontColor);var f=spider.drawing.context;f.beginPath();f.moveTo(a,c);f.lineTo(b,d);f.strokeStyle=spider_helper_ColorToHtml(e);f.stroke()}
function spider_DrawText(a,c,b,d,e){"undefined"===typeof d&&(d=spider.drawing.frontColor);e=spider.drawing.context;e.fillStyle=spider_helper_ColorToHtml(d);e.fillText(b,a,c+spider_2ddrawing_getTextHeight(spider.drawing.context.font).ascent)}
function spider_Circle(a,c,b,d){"undefined"===typeof d&&(d=spider.drawing.frontColor);var e=spider.drawing.context;4==spider.drawing.mode?(e.beginPath(),e.arc(a,c,b-1,0,2*Math.PI,!1),e.strokeStyle=spider_helper_ColorToHtml(d),e.stroke()):(e.beginPath(),e.arc(a,c,b,0,2*Math.PI,!1),e.fillStyle=spider_helper_ColorToHtml(d),e.fill())}
function spider_Ellipse(a,c,b,d,e){function f(a,d,e,b,c){var f=b/2*0.5522848,h=c/2*0.5522848,g=d+b,k=e+c;b=d+b/2;c=e+c/2;a.beginPath();a.moveTo(d,c);a.bezierCurveTo(d,c-h,b-f,e,b,e);a.bezierCurveTo(b+f,e,g,c-h,g,c);a.bezierCurveTo(g,c+h,b+f,k,b,k);a.bezierCurveTo(b-f,k,d,c+h,d,c);a.closePath()}"undefined"===typeof e&&(e=spider.drawing.frontColor);var g=spider.drawing.context;4==spider.drawing.mode?(f(g,a-b,c-d,2*b,2*d),g.strokeStyle=spider_helper_ColorToHtml(e),g.stroke()):(f(g,a-b,c-d,2*b,2*d),g.fillStyle=
spider_helper_ColorToHtml(e),g.fill())}function spider_DrawingFont(a){spider.drawing.context.font=a.name}function spider_DrawingMode(a){spider.drawing.mode=a}function spider_StopDrawing(){spider.drawing.stopDrawingCallback&&spider.drawing.stopDrawingCallback(spider.drawing.output)}
function spider_RoundBox(a,c,b,d,e,f,g){function l(a,b,c,d,e,f){"undefined"===typeof f&&(f=5);a.beginPath();a.moveTo(b+f,c);a.lineTo(b+d-f,c);a.quadraticCurveTo(b+d,c,b+d,c+f);a.lineTo(b+d,c+e-f);a.quadraticCurveTo(b+d,c+e,b+d-f,c+e);a.lineTo(b+f,c+e);a.quadraticCurveTo(b,c+e,b,c+e-f);a.lineTo(b,c+f);a.quadraticCurveTo(b,c,b+f,c);a.closePath()}f=spider.drawing.context;4==spider.drawing.mode?(l(f,a+0.5,c+0.5,b,d,e),f.strokeStyle=spider_helper_ColorToHtml(g),f.stroke()):(l(f,a+0.5,c+0.5,b,d,e),f.fillStyle=
spider_helper_ColorToHtml(g),f.fill())}function spider_RGB(a,c,b){return b<<16|c<<8|a}function spider_RGBA(a,c,b,d){return d<<24|b<<16|c<<8|a}function spider_Red(a){return a&255}function spider_Green(a){return a>>8&255}function spider_Blue(a){return a>>16&255}function spider_Alpha(a){return a>>24&255}function spider_BackColor(a){return spider.drawing.backColor=a}function spider_FrontColor(a){return spider.drawing.frontColor=a}
function spider_TextHeight(a){a=spider_2ddrawing_getTextHeight(spider.drawing.context.font);return a.ascent+a.descent}function spider_TextWidth(a){return Math.ceil(spider.drawing.context.measureText(a).width)};

spider.desktop={mouseX:-1,mouseY:-1};function spider_DesktopWidth(a){return $(window).width()}function spider_DesktopHeight(a){return $(window).height()}function spider_InitDesktop(){$(document).on({mouseout:function(a){spider.desktop.mouseX=-1;spider.desktop.mouseY=-1},mouseenter:function(a){spider.desktop.mouseX=a.clientX;spider.desktop.mouseY=a.clientY},mousemove:function(a){spider.desktop.mouseX=a.clientX;spider.desktop.mouseY=a.clientY}})}
function spider_DesktopMouseX(){return spider.desktop.mouseX}function spider_DesktopMouseY(){return spider.desktop.mouseY}function spider_DesktopX(a){return 0}function spider_DesktopY(a){return 0}function spider_ExamineDesktops(){return 1}function spider_DesktopDepth(a){return screen.colorDepth}function spider_DesktopName(a){return navigator.userAgent};

function spider_InitList(){}function spider_NewList(a,b,c){var d=new spider_SysList;d.type=a;d.field=b;d.isNative=c;return d}
function spider_AddElement(a){var b=new a.type;a.nbElements++;if(a.current){b.previous=a.current;if(b.next=a.current.next)a.current.next.previous=b;a.current.next=b;a.current=b;a.index++}else a.first&&(a.first.previous=b),a.current=b,b.next=a.first,b.previous=null,a.index=0,a.isIndexInvalid=!1;a.current.previous||(a.first=a.current);a.current.next||(a.last=a.current);return b}
function spider_InsertElement(a){var b=new a.type;a.nbElements++;if(a.current){b.next=a.current;if(b.previous=a.current.previous)a.current.previous.next=b;a.current.previous=b;a.current=b}else a.first&&(a.first.previous=b),a.current=b,a.current.next=a.first,a.current.previous=null,a.index=0,a.isIndexInvalid=!1;a.current.previous||(a.first=a.current);a.current.next||(a.last=a.current);return b}
function spider_ListIndex(a){if(a.isIndexInvalid){var b=-1,c=a.current;if(c){for(;c;)b++,c=c.previous;a.index=b;a.isIndexInvalid=!1}return b}return a.index}function spider_LastElement(a){a.current=a.last;return a.current?(a.isIndexInvalid=!1,a.index=a.nbElements-1,a.current):0}
function spider_MergeLists(a,b,c){"undefined"===typeof c&&(c=2);if(a.first){3!=c||b.current&&b.current!=b.first?4!=c||b.current&&b.current!=b.last||(c=2):c=1;if(b.first)switch(c){case 3:a.first.previous=b.current.previous;b.current.previous.next=a.first;b.current.previous=a.last;a.last.next=b.current;b.isIndexInvalid=!0;break;case 4:b.current.next.previous=a.last;a.last.next=b.current.next;a.first.previous=b.current;b.current.next=a.first;break;case 1:a.last.next=b.first;b.first.previous=a.last;b.first=
a.first;b.isIndexInvalid=!0;break;default:a.first.previous=b.last,b.last.next=a.first,b.last=a.last}else b.first=a.first,b.last=a.last;b.nbElements+=a.nbElements;a.current=null;a.first=null;a.last=null;a.nbElements=0;a.isIndexInvalid=!0}}
function spider_MoveElement(a,b,c){function d(a){a.current.previous&&(a.current.previous.next=a.current.next);a.current.next&&(a.current.next.previous=a.current.previous);a.current==a.first&&(a.first=a.current.next);a.current==a.last&&(a.last=a.current.previous)}var e;if(e=a.current)switch(b){case 1:e!=a.first&&(d(a),e.previous=0,e.next=a.first,a.first.previous=e,a.first=e,a.index=0,a.isIndexInvalid=0);break;case 2:e!=a.last&&(d(a),e.previous=a.last,e.next=0,a.last.next=e,a.last=e,a.index=a.nbElements-
1,a.isIndexInvalid=0);break;case 3:c&&e!=c&&(d(a),e.next=c,e.previous=c.previous,c.previous=e,e.previous&&(e.previous.next=e),c==a.first&&(a.first=e),a.isIndexInvalid=1);break;case 4:c&&e!=c&&(d(a),e.previous=c,e.next=c.next,c.next=e,e.next&&(e.next.previous=e),c==a.last&&(a.last=e),a.isIndexInvalid=1)}}function spider_NextElement(a){var b;if(a.current){if(b=a.current.next)a.current=b,a.index++}else b=a.first,a.current=b,a.index=0;return b}
function spider_PushListPosition(a){a.stack||(a.stack=[]);a.stack.push(a.current)}function spider_PopListPosition(a){a.stack&&0<a.stack.length&&(a.isIndexInvalid=!0,a.current=a.stack.pop())}function spider_PreviousElement(a){var b;a.current&&(b=a.current.previous)&&(a.current=b,a.index--);return b}function spider_ResetList(a){a.isIndexInvalid=!0;a.current=null}function spider_ListSize(a){return a.nbElements}function spider_ChangeCurrentElement(a,b){a.isIndexInvalid=!0;a.current=b}
function spider_CopyList(a,b){spider_ClearList(b);var c,d;for(c=a.first;c;)d=spider_AddElement(b),c.copy(d),c=c.next}function spider_ClearList(a){a.current=null;a.first=null;a.last=null;a.nbElements=0;a.isIndexInvalid=!0}
function spider_DeleteElement(a,b){"undefined"===typeof b&&(b=0);if(a.current){a.nbElements--;var c=a.current.previous,d=a.current.next;c||d?c?(d?(c.next=d,d.previous=c,a.current=c):(c.next=null,a.current=c,a.last=c),a.index--):(d.previous=null,a.current=null,a.first=d,b&1?(a.current=d,a.index=0,a.isIndexInvalid=!1):(a.current=null,a.isIndexInvalid=!0)):(a.current=null,a.first=null,a.last=null,a.isIndexInvalid=!0)}}function spider_FreeList(a){a&&spider.ClearList(a)}
function spider_FirstElement(a){a.current=a.first;return a.current?(a.isIndexInvalid=!1,a.index=0,a.current):0}
function spider_SelectElement(a,b){var c,d;d=a.index;a.index=b;if(0>b||b>=a.nbElements)c=null;else if(a.isIndexInvalid)if(b<a.nbElements/2)for(c=a.first;c&&0<b;)c=c.next,b--;else for(c=a.last,b=a.nbElements-1-b;c&&0<b;)c=c.previous,b--;else if(b>d)if(c=a.current,b-d<a.nbElements-b)for(b-=d;c&&0<b;)c=c.next,b--;else for(c=a.last,b=a.nbElements-1-b;c&&0<b;)c=c.previous,b--;else if(d-b<b)for(c=a.current,b=d-b;c&&0<b;)c=c.previous,b--;else for(c=a.first;c&&0<b;)c=c.next,b--;if(a.current=c)return a.isIndexInvalid=
!1,c;a.isIndexInvalid=!0;return null}function spider_SplitList(a,b,c){var d,e=0;spider_ClearList(b);if(a.current){c?c=a.current.next:(c=a.current,a.current.previous?(a.current=a.current.previous,a.index--):(a.current=null,a.isIndexInvalid=1));if(c)for(d=a.last,c.previous&&(c.previous.next=null),a.first==c&&(a.first=null),a.last=c.previous,b.first=c,b.last=d,c.previous=null,d.next=null;c;)e++,c=c.next;a.nbElements-=e;b.nbElements=e}}
function spider_SwapElements(a,b,c){var d,e;b!=c&&(a.isIndexInvalid=1,d=c.next,e=c.previous,b.next==c?(c.next=b,c.previous=b.previous,b.next=d,b.previous=c,c.previous?c.previous.next=c:a.first=c,b.next?b.next.previous=b:a.last=b):b.previous==c?(c.next=b.next,c.previous=b,b.next=c,b.previous=e,c.next?c.next.previous=c:a.last=c,b.previous?b.previous.next=b:a.first=b):(b.next?b.next.previous=c:a.last=c,c.next=b.next,b.previous?b.previous.next=c:a.first=c,c.previous=b.previous,d?d.previous=b:a.last=b,
b.next=d,e?e.next=b:a.first=b,b.previous=e))};

var dijit;
(function(){function D(d){var f;if(-1==d)spider.gadget.objects.CleanAll();else if(f=spider.gadget.objects.Get(d))f.div.parentNode&&f.div.parentNode.removeChild(f.div),f.gadget instanceof dijit._WidgetBase&&f.gadget.destroy(),spider.gadget.objects.Remove(d)}function s(d,f,g,k,n){d.style.position="absolute";d.style.left=f+"px";d.style.top=g+"px";d.style.width=k+"px";d.style.height=n+"px"}function q(d,f){d.isDisabled||spider.event.Send(1,d.windowId,d.id,f)}function v(d,f,g,k,n){d.domNode.style.position="absolute";
d.domNode.style.left=f+"px";d.domNode.style.top=g+"px";d.domNode.style.width=k+"px";d.domNode.style.height=n+"px"}function u(d){var f=$(d).cssValue("paddingLeft")+$(d).cssValue("paddingRight")+$(d).cssValue("borderLeftWidth")+$(d).cssValue("borderRightWidth");d=$(d).cssValue("paddingTop")+$(d).cssValue("paddingBottom")+$(d).cssValue("borderTopWidth")+$(d).cssValue("borderBottomWidth");return{x:f,y:d}}function x(d,f,g){var k=spider.gadget.context;f||(d=$(spider_WindowID(d.windowId).contentFrame),f=
$(d).css("fontSize")+" "+$(d).css("fontFamily"));k.font=f;d=spider_2ddrawing_getTextHeight(k.font);d=d.ascent+d.descent;return{width:Math.ceil(k.measureText(g).width),height:d}}function z(d,f,g){var k;$(d).find(f).each(function(){if(-1<$(this).attr("class").search(g))return k=this,!1});return k}function B(d,f,g,k){k?($(f).css("background-color",""),$(g).css("color","")):(d.backColor&&-1!=d.backColor&&d.SetGadgetColor(2,d.backColor),d.frontColor&&-1!=d.frontColor&&d.SetGadgetColor(1,d.frontColor));
d.gadget.set("disabled",k?!0:!1)}function A(d,f,g,k,n){switch(k){case 2:d.gadget.get("disabled")||$(f).css("background-color",spider_helper_ColorToHtml(n));d.backColor=n;break;case 1:d.gadget.get("disabled")||$(g).css("color",spider_helper_ColorToHtml(n)),d.frontColor=n}}function E(d){d.gadget instanceof dijit._WidgetBase&&d.gadget.set("_onChangeActive",!1)}function F(d){d.gadget instanceof dijit._WidgetBase&&d.gadget.set("_onChangeActive",!0)}function G(d,f){null===f&&(f=0);var g;if(g=spider.gadget.objects.Get(d))if(g.GadgetHeight)g.GadgetHeight(f);
else if(1!=f)return $(g.div).height();return 0}function H(d,f){null===f&&(f=0);var g;if(g=spider.gadget.objects.Get(d))if(g.GadgetWidth)g.GadgetWidth(f);else if(1!=f)return $(g.div).width();return 0}function I(d){var f;return(f=spider.gadget.objects.Get(d))?parseInt($(f.div).css("left"),10):null}function J(d){var f;return(f=spider.gadget.objects.Get(d))?parseInt($(f.div).css("top"),10):null}spider.nbModules++;require("dijit/dijit dojo/store/Memory dojo/store/Observable dojo/_base/declare dojo/aspect dojo/_base/lang dgrid/OnDemandGrid dgrid/Selection dgrid/Keyboard dgrid/extensions/ColumnResizer cbtree/store/Hierarchy dijit/tree/ObjectStoreModel cbtree/model/ForestStoreModel dgrid/TouchScroll dijit/form/SimpleTextarea dijit/form/Button dijit/form/ToggleButton dijit/form/RadioButton dijit/form/ComboBox dijit/form/Select dijit/form/CheckBox dijit/form/Textarea dijit/form/SimpleTextarea dijit/form/NumberTextBox dijit/form/HorizontalSlider dijit/form/VerticalSlider dijit/ProgressBar dijit/Tooltip dijit/layout/TabContainer dijit/form/NumberSpinner dijit/form/DateTextBox dijit/Tree dijit/tree/ObjectStoreModel dijit/Calendar dijit/focus dijit/registry dijit/Toolbar dijit/ToolbarSeparator dijit/Menu dijit/MenuItem dijit/MenuSeparator dijit/DropDownMenu dijit/MenuBar dijit/PopupMenuBarItem dijit/PopupMenuItem dijit/layout/ContentPane dijit/layout/BorderContainer dojo/dom-style dojo/data/ItemFileWriteStore cbtree/Tree cbtree/store/Hierarchy cbtree/store/ObjectStore cbtree/model/ForestStoreModel dgrid/Grid dgrid/extensions/ColumnReorder dojo/domReady!".split(" "),
function(d,f,g,k,n,m,b,e,c,h,a,l,p,r,t){spider.nbLoadedModules++;dijit=d;spider.StoreMemory=f;spider.StoreObservable=g;spider.DojoBaseDeclare=k;spider.DojoAspect=n;spider.DojoBaseLang=m;spider.DGridOnDemandGrid=b;spider.DGridSelection=e;spider.DGridKeyboard=c;spider.DGridColumnResizer=h;spider.CBTreeStoreHierarchy=a;spider.TreeObjectStoreModel=l;spider.CBTreeModelForestStoreModel=p;spider.DGridTouchScroll=r;spider.DojoDomStyle=t;SpiderMain()});spider.gadget={defaultFont:null,objects:new spider.object(D),
optionGroupCount:0,lastType:null,register:function(d,f,g,k){this.lastType=f;d.type=f;d.div=g;d.gadget=k;d.windowId=spider.window.currentWindowId;d.userData=0;k.spiderId=d.id;spider.window.gadgetList.get().appendChild(g)}};window.spider_InitGadget=function(){};window.spider_AddGadgetColumn=function(d,f,g,k){var n;(n=spider.gadget.objects.Get(d))&&n.AddGadgetColumn&&n.AddGadgetColumn(f,g,k)};window.spider_AddGadgetItem=function(d,f,g,k,n){"undefined"===typeof k&&(k=null);"undefined"===typeof n&&(n=
0);var m;(m=spider.gadget.objects.Get(d))&&m.AddGadgetItem&&m.AddGadgetItem(f,g,k,n)};window.spider_BindGadgetEvent=function(d,f,g){"undefined"===typeof g&&(g=-1);var k;(k=spider.gadget.objects.Get(d))&&spider_BindEvent(1,f,k.windowId,k.id,g)};window.spider_ButtonGadget=function(d,f,g,k,n,m,b){"undefined"===typeof b&&(b=0);var e=spider.gadget.objects.Allocate(d),c=new (b&16?dijit.form.ToggleButton:dijit.form.Button)({label:m,showLabel:!0,onClick:function(){q(e,0)}}),h=document.createElement("div");
h.appendChild(c.domNode);b&16?(c.attr("iconClass","dijitCheckBoxIcon"),$(c.focusNode).css("display","table-cell")):$(c.containerNode).css("display","table-cell");b&8&&$(c.containerNode).css("white-space","normal");b&2?($(c.containerNode).css("text-align","left"),$(c.containerNode).css("padding-left","5px")):b&1&&($(c.containerNode).css("text-align","right"),$(c.containerNode).css("padding-right","5px"));e.GetGadgetText=function(){return c.get("label")};e.SetGadgetText=function(a){c.set("label",a)};
e.GetGadgetState=function(){return b&16?c.get("checked")?1:0:0};e.SetGadgetState=function(a){b&16&&c.set("checked",a)};e.GetRequiredSize=function(){var a=$(h).css("fontSize")+" "+$(h).css("fontFamily"),a=x(e,a,e.GetGadgetText());a.width+=16;a.height+=8;return a};e.ResizeGadget=function(a,d,e,f){s(h,a,d,e,f);a=z(h,"span","dijitButtonNode");a=u(a);$(c.titleNode).width(e-a.x);$(c.titleNode).height(f-a.y);0===(b&16)&&($(c.containerNode).width(e-a.x),$(c.containerNode).height(f-a.y))};spider.gadget.register(e,
1,h,c);e.ResizeGadget(f,g,k,n);return e.resultId};window.spider_ButtonImageGadget=function(d,f,g,k,n,m,b){"undefined"===typeof b&&(b=0);var e=spider.gadget.objects.Allocate(d),c=new (b&16?dijit.form.ToggleButton:dijit.form.Button)({label:"",showLabel:!1,iconClass:spider.image.GetCSS(m),onClick:function(){q(e,0)}}),h=document.createElement("div");h.appendChild(c.domNode);$(c.titleNode).css("display","table-cell");e.GetGadgetAttribute=function(a){switch(a){case 1:return null;case 2:return null}return 0};
e.SetGadgetAttribute=function(a,b){switch(a){case 1:c.attr("iconClass",spider.image.GetCSS(b))}};e.ResizeGadget=function(a,b,e,d){s(h,a,b,e,d);a=z(h,"span","dijitButtonNode");a=u(a);$(c.titleNode).width(e-a.x);$(c.titleNode).height(d-a.y)};spider.gadget.register(e,19,h,c);e.ResizeGadget(f,g,k,n);return e.resultId};window.spider_CalendarGadget=function(d,f,g,k,n,m,b){function e(a){return new Date(spider_Year(a),spider_Month(a)-1,spider_Day(a))}function c(a){return spider_Date(a.getFullYear(),a.getMonth()+
1,a.getDate(),0,0,0)}"undefined"===typeof m&&(m=spider_Date());"undefined"===typeof b&&(b=0);var h=spider.gadget.objects.Allocate(d),a=new dijit.Calendar({constraints:{min:new Date(1970,0,0),max:new Date(2035,0,0)},isDisabledDate:function(b){if(a&&!h.isDisabled){var c=a.attr("constraints");return!(b>=c.min&&b<=c.max)}return!0},onChange:function(){q(h,9)}}),l=document.createElement("div");l.appendChild(a.domNode);h.DisableGadget=function(b){h.isDisabled=b;a._populateGrid()};h.GetGadgetState=function(){var b=
a.get("value");return c(b)};h.SetGadgetState=function(b){a.set("value",e(b))};h.GetGadgetAttribute=function(b){switch(b){case 1:return c(a.attr("constraints").min);case 2:return c(a.attr("constraints").max)}return 0};h.SetGadgetAttribute=function(b,c){var d=a.attr("constraints");switch(b){case 1:d.min=e(c);a.attr("constraints",d);a._populateGrid();break;case 2:d.max=e(c),a.attr("constraints",d),a._populateGrid()}};h.GetRequiredSize=function(){var a={width:6,height:6};$.each($(l).children(),function(b,
c){a.width+=$(c).outerWidth(!0);a.height+=$(c).outerHeight(!0)});return a};h.ResizeGadget=function(b,c,d,e){s(l,b,c,d,e);v(a,0,0,d,e)};spider.gadget.register(h,2,l,a);h.ResizeGadget(f,g,k,n);h.SetGadgetState(m);a._populateGrid();return h.resultId};window.spider_CanvasGadget=function(d,f,g,k,n,m){"undefined"===typeof m&&(m=0);var b=spider.gadget.objects.Allocate(d),e=document.createElement("canvas");b.canvas=e;b.mouseX=0;b.mouseY=0;b.mouseWheelDelta=0;b.buttons=0;b.lastKey=0;b.lastInput=0;b.modifiers=
0;m&4&&e.setAttribute("tabindex","0");$(e).on({click:function(){q(b,0)},dblclick:function(){q(b,2)},mouseover:function(c){q(b,65537)},mouseout:function(c){q(b,65538)},mousemove:function(c){var a=e.getBoundingClientRect();b.mouseX=c.clientX-a.left;b.mouseY=c.clientY-a.top;q(b,65539)},mousedown:function(c){var a;0===c.button?(a=65540,b.buttons|=1):1===c.button?(a=65544,b.buttons|=4):2===c.button&&(a=65542,b.buttons|=2);q(b,a);if(1===c.button)return!1},mouseup:function(c){var a;0===c.button?(a=65541,
b.buttons&=-2):1===c.button?(a=65545,b.buttons&=-5):2===c.button&&(a=65543,b.buttons&=-3);q(b,a)},focus:function(){q(b,7)},blur:function(){q(b,8)},contextmenu:function(c){return!1},mousewheel:function(c){c||(c=event);b.mouseWheelDelta=0>c.detail||0<c.wheelDelta?1:-1;q(b,65546);return!1},keydown:function(c){b.lastKey=c.keyCode;16==c.keyCode&&(b.modifiers|=1);17==c.keyCode&&(b.modifiers|=4);18==c.keyCode&&(b.modifiers|=2);q(b,65547)},keyup:function(c){b.lastKey=c.keyCode;16==c.keyCode&&(b.modifiers&=
-2);17==c.keyCode&&(b.modifiers&=-5);18==c.keyCode&&(b.modifiers&=-3);q(b,65548)},keypress:function(c){b.lastInput=c.which;b.lastInput&&q(b,65549)}});var c=document.createElement("div");c.appendChild(e);m&1&&$(c).addClass("sbCanvasBorder");b.DisableGadget=function(c){};b.GetGadgetAttribute=function(c){switch(c){case 1:return e;case 4:return b.buttons;case 2:return b.mouseX;case 3:return b.mouseY;case 8:return b.mouseWheelDelta;case 5:return b.lastKey;case 9:return b.lastInput;case 6:return b.modifiers}};
b.SetGadgetAttribute=function(c,a){switch(c){case 7:switch(b.cursor=a,a){case 0:e.style.cursor="default";b.cursor=-1;break;case 3:e.style.cursor="pointer";break;case 1:e.style.cursor="crosshair";break;case 2:e.style.cursor="text";break;case 4:e.style.cursor="wait";break;case 5:e.style.cursor="no-drop";break;case 6:e.style.cursor="move";break;case 7:e.style.cursor="w-resize";break;case 6:e.style.cursor="s-resize";break;case 8:e.style.cursor="se-resize";break;case 9:e.style.cursor="sw-resize";break;
case 10:e.style.cursor="none"}}};b.ResizeGadget=function(b,a,d,f){var g=u(c);e.width=d-g.x;e.height=f-g.y;s(c,b,a,d-g.x,f-g.y)};spider.gadget.register(b,33,c,e);b.ResizeGadget(f,g,k,n);return b.resultId};window.spider_CanvasOutput=function(d){var f;return(f=spider.gadget.objects.Get(d))?{gadget:f,canvas:f.canvas,context:f.canvas.getContext("2d"),stopDrawingCallback:null}:null};window.spider_CheckBoxGadget=function(d,f,g,k,n,m,b){"undefined"===typeof b&&(b=0);var e=spider.gadget.objects.Allocate(d);
d="spidercheckbox_"+e.id;var c=new dijit.form.CheckBox({id:d,onClick:function(){q(e,0)}}),h=document.createElement("div"),a=document.createElement("span");a.className="sbVerticalCenter";h.appendChild(a);a.appendChild(c.domNode);var l=put(a,"label",{htmlFor:d});$(l).css("padding-left","5px");c.label=l;b&1?$(l).css("text-align","right"):b&2&&$(l).css("text-align","center");e.DisableGadget=function(a){$(l).css("color",a?"gray":"");c.set("disabled",a?!0:!1)};e.GetGadgetState=function(){return c.get("checked")?
1:0};e.SetGadgetState=function(a){-1==a?c.set("value","mixed"):c.set("checked",a)};e.GetGadgetText=function(){return l.innerHTML};e.SetGadgetText=function(c){l.innerHTML=c;""===c?a.removeChild(l):a.appendChild(l)};e.GetRequiredSize=function(){var a=$(h).css("fontSize")+" "+$(h).css("fontFamily"),a=x(e,a,e.GetGadgetText());a.width+=28;a.height+=6;return a};e.ResizeGadget=function(c,b,d,e){s(h,c,b,d,e);$(a).width(d);$(a).height(e)};spider.gadget.register(e,4,h,c);c.startup();e.SetGadgetText(m);e.ResizeGadget(f,
g,k,n);return e.resultId};window.spider_ClearGadgetItems=function(d){var f;(f=spider.gadget.objects.Get(d))&&f.ClearGadgetItems&&f.ClearGadgetItems()};window.spider_CloseGadgetList=function(){spider.window.gadgetList.pop()};window.spider_ComboBoxGadget=function(d,f,g,k,n,m){"undefined"===typeof m&&(m=0);var b=spider.gadget.objects.Allocate(d),e=0,c=spider_NewList(function(){return{id:null,text:null}}),h=new spider.StoreMemory,a=new dijit.form.ComboBox({store:h,onChange:function(){q(b,9)},onFocus:function(){q(b,
7)},onBlur:function(){q(b,8)}});m&1||$(a.focusNode).attr("readOnly",!0);var l=document.createElement("div");l.appendChild(a.domNode);$(a._buttonNode).css("height","100%");var p=-1;a.watch("item",function(a,c,b){p=b.id});b.GetGadgetState=function(){return p};b.SetGadgetState=function(c){a.set("value",h.get(c).name);p=c};b.GetGadgetText=function(){return a.get("value")};b.SetGadgetText=function(c){a.set("value",c);p=-1};b.AddGadgetItem=function(a,b,d,l){-1==a&&(a=spider_ListSize(c));0>=a?spider_ResetList(c):
spider_SelectElement(c,a-1);a=spider_AddElement(c);a.id=e;a.text=b;h.add({name:"",id:e});b=spider_ListIndex(c);do h.put({name:a.text},h.get(b)),b++;while(a=spider_NextElement(c));e++};b.ClearGadgetItems=function(){spider_ClearList(c);h=new spider.StoreMemory;a.set("store",h);e=0};b.CountGadgetItems=function(){return spider_ListSize(c)};b.SetGadgetColor=function(c,d){A(b,a.focusNode.parentNode,a.focusNode,c,d)};b.GetGadgetItemData=function(a){var b;return(b=spider_SelectElement(c,a))?b.data?b.data:
0:0};b.SetGadgetItemData=function(a,b){var d;if(d=spider_SelectElement(c,a))d.data=b};b.GetGadgetItemText=function(a,b){var d;return(d=spider_SelectElement(c,a))?d.text:""};b.SetGadgetItemText=function(a,b,d){if(d=spider_SelectElement(c,a))d.text=b,a=h.get(a),a.name=b,h.put(a)};b.GetRequiredSize=function(){var a=$(l).css("fontSize")+" "+$(l).css("fontFamily"),a=x(b,a,"Hg");a.width=50;a.height+=5;return a};b.ResizeGadget=function(c,b,d,e){s(l,c,b,d,e);c=u(a.domNode);v(a,0,0,d-c.x,e-c.y);"claro"==spider.gadgetTheme?
$(a.focusNode).height(e-c.y-2):$(a.focusNode).height(e-c.y)};spider.gadget.register(b,8,l,a);b.ResizeGadget(f,g,k,n);return b.resultId};window.spider_ContainerGadget=function(d,f,g,k,n,m){var b=spider.gadget.objects.Allocate(d);"undefined"===typeof m&&(m=0);var e=new dijit.layout.ContentPane({style:"overflow: hidden; padding: 0px;",content:""}),c=document.createElement("div");e.placeAt(c);m&1&&$(c).addClass("sbContainerBorder");b.GetGadgetColor=function(c){return 2==c?b.backColor?b.backColor:-1:-1};
b.SetGadgetColor=function(d,a){2==d&&($(c).css("background-color",spider_helper_ColorToHtml(a)),b.backColor=a)};b.ResizeGadget=function(b,a,d,f){var g=u(c);s(c,b,a,d-g.x,f-g.y);v(e,0,0,d-g.x,f-g.y);e.resize()};spider.DojoAspect.after(e,"resize",function(c,a){q(b,0)});spider.gadget.register(b,11,c,e);spider.window.gadgetList.push(e.domNode);b.ResizeGadget(f,g,k,n);return b.resultId};window.spider_CountGadgetItems=function(d){var f;return(f=spider.gadget.objects.Get(d))&&f.CountGadgetItems?f.CountGadgetItems():
0};window.spider_DateGadget=function(d,f,g,k,n,m,b,e){function c(a){a=spider_ReplaceString(a,"%yyyy","yyyy");a=spider_ReplaceString(a,"%mm","MM");return a=spider_ReplaceString(a,"%dd","dd")}function h(a){return new Date(spider_Year(a),spider_Month(a)-1,spider_Day(a))}function a(a){return spider_Date(a.getFullYear(),a.getMonth()+1,a.getDate(),0,0,0)}"undefined"===typeof m&&(m="%yyyy/%mm/%dd");"undefined"===typeof b&&(b=spider_Date());"undefined"===typeof e&&(e=0);var l=spider.gadget.objects.Allocate(d),
p=new dijit.form.DateTextBox({constraints:{min:new Date(1970,0,0),max:new Date(2035,0,0),datePattern:c(m)},onChange:function(){q(l,9)}});$(p._buttonNode).css("height","100%");var r=document.createElement("div");r.appendChild(p.domNode);l.DisableGadget=function(a){B(l,p.focusNode.parentNode,p.focusNode,a)};l.GetGadgetText=function(){return p.get("displayedValue")};l.SetGadgetText=function(a){var b=p.get("value");p.attr("constraints").datePattern=c(a);p.set("value",b)};l.GetGadgetState=function(){return a(p.get("value"))};
l.SetGadgetState=function(a){p.set("value",h(a))};l.GetGadgetAttribute=function(c){switch(c){case 1:return a(p.attr("constraints").min);case 2:return a(p.attr("constraints").max)}return 0};l.SetGadgetAttribute=function(a,c){var b=p.attr("constraints");switch(a){case 1:b.min=h(c);p.attr("constraints",b);break;case 2:b.max=h(c),p.attr("constraints",b)}};l.GetGadgetColor=function(a){switch(a){case 2:return l.backColor?l.backColor:-1;case 1:return l.frontColor?l.frontColor:-1}return-1};l.SetGadgetColor=
function(a,c){A(l,p.focusNode.parentNode,p.focusNode,a,c)};l.GetRequiredSize=function(){var a=$(r).css("fontSize")+" "+$(r).css("fontFamily"),a=x(l,a,"Hg");a.width=60;a.height+=5;return a};l.ResizeGadget=function(a,c,b,d){s(r,a,c,b,d);a=u(p._popupStateNode);v(p,0,0,b-a.x,d-a.y);"claro"==spider.gadgetTheme?$(p.focusNode).height(d-a.y-2):$(p.focusNode).height(d-a.y)};spider.gadget.register(l,2,r,p);l.SetGadgetState(b);l.ResizeGadget(f,g,k,n);return l.resultId};window.spider_DisableGadget=function(d,
f){var g;if(g=spider.gadget.objects.Get(d))g.DisableGadget?g.DisableGadget(f):g.gadget.set("disabled",f?!0:!1)};window.spider_EditorGadget=function(d,f,g,k,n,m){"undefined"===typeof m&&(m=0);var b=spider.gadget.objects.Allocate(d),e=new dijit.form.SimpleTextarea({style:"overflow: auto; resize: none;",intermediateChanges:!0,onChange:function(){q(b,9)},onFocus:function(){q(b,7)},onBlur:function(){q(b,8)}});d=e.domNode;var c=document.createElement("div");c.appendChild(d);b.editor=e;m&2||$(e.focusNode).attr("wrap",
"off");m&1&&$(e.focusNode).attr("readOnly",!0);b.DisableGadget=function(c){B(b,e.focusNode,e.focusNode,c)};b.GetGadgetText=function(){return e.get("value")};b.SetGadgetText=function(c){e.set("value",c)};b.GetGadgetAttribute=function(c){switch(c){case 2:return"off"==$(e.focusNode).attr("wrap")?0:1;case 1:return $(e.focusNode).attr("readOnly")?1:0}return 0};b.SetGadgetAttribute=function(c,a){switch(c){case 2:$(e.focusNode).attr("wrap",a?"":"off");break;case 1:$(e.focusNode).attr("readOnly",a?!0:!1)}};
b.GetGadgetColor=function(c){switch(c){case 2:return b.backColor?b.backColor:-1;case 1:return b.frontColor?b.frontColor:-1}return-1};b.SetGadgetColor=function(c,a){A(b,e.focusNode,e.focusNode,c,a)};b.SetActiveGadget=function(){require(["dijit/focus"],function(c){c.focus(e.focusNode)})};b.ResizeGadget=function(b,a,d,f){s(c,b,a,d,f);b=u(e.focusNode);v(e,0,0,d-b.x,f-b.y)};spider.gadget.register(b,22,c,e);b.ResizeGadget(f,g,k,n);return b.resultId};window.spider_FrameGadget=function(d,f,g,k,n,m,b){"undefined"===
typeof b&&(b=0);d=spider.gadget.objects.Allocate(d);var e=document.createElement("fieldset");$(e).css("margin",0);$(e).addClass("sbFrameBorder");var c=document.createElement("div");c.appendChild(e);var h=document.createElement("legend");d.legend=h;d.GetGadgetText=function(){return h.innerHTML};d.SetGadgetText=function(a){h.innerHTML=a;""===a?e.hasChildNodes()&&e.removeChild(h):e.appendChild(h)};d.GetRequiredSize=function(){var a={width:0,height:0};$.each($(c).children(),function(c,b){a.width+=$(b).outerWidth(!0);
a.height+=$(b).outerHeight(!0)});var b=u(e);a.width-=b.x;a.height-=b.y;return a};d.ResizeGadget=function(a,b,d,f){s(c,a,b,d,f);a=u(e);s(e,0,0,d-a.x,f-a.y)};d.SetGadgetText(m);spider.gadget.register(d,7,c,e);d.ResizeGadget(f,g,k,n);return d.resultId};window.spider_FreeGadget=D;window.spider_GadgetHeight=G;window.spider_GadgetID=function(d){var f;return(f=spider.gadget.objects.Get(d))?f:null};window.spider_GadgetToolTip=function(d,f){var g;if(g=spider.gadget.objects.Get(d))g.tooltip||(g.tooltip=new dijit.Tooltip({connectId:g.div})),
g.tooltip.set("label",f)};window.spider_GadgetType=function(d){if(d=spider.gadget.objects.Get(d))return d.type};window.spider_GadgetWidth=H;window.spider_GadgetX=I;window.spider_GadgetY=J;window.spider_GetActiveGadget=function(){var d=-1;require(["dijit/focus","dijit/registry"],function(f,g){var k;k=f.curNode;for(var n;!n&&k;)n=g.byNode(k),k=k.parentElement?k.parentElement:null;(k=n)&&k.hasOwnProperty("spiderId")&&(d=k.spiderId)});return d};window.spider_GetGadgetAttribute=function(d,f){var g;return(g=
spider.gadget.objects.Get(d))&&g.GetGadgetAttribute?g.GetGadgetAttribute(f):0};window.spider_GetGadgetColor=function(d,f){var g;return(g=spider.gadget.objects.Get(d))&&g.GetGadgetColor?g.GetGadgetColor(f):0};window.spider_GetGadgetData=function(d){var f;return(f=spider.gadget.objects.Get(d))?f.userData:0};window.spider_GetGadgetItemAttribute=function(d,f,g,k){"undefined"===typeof k&&(k=-1);var n;return(n=spider.gadget.objects.Get(d))&&n.GetGadgetItemAttribute?n.GetGadgetItemAttribute(f,g,k):0};window.spider_GetGadgetItemData=
function(d,f){var g;return(g=spider.gadget.objects.Get(d))&&g.GetGadgetItemData?g.GetGadgetItemData(f):0};window.spider_GetGadgetItemState=function(d,f){var g;return(g=spider.gadget.objects.Get(d))&&g.GetGadgetItemState?g.GetGadgetItemState(f):0};window.spider_GetGadgetItemText=function(d,f,g){"undefined"===typeof g&&(g=-1);var k;return(k=spider.gadget.objects.Get(d))&&k.GetGadgetItemText?k.GetGadgetItemText(f,g):""};window.spider_GetGadgetState=function(d){var f;return(f=spider.gadget.objects.Get(d))&&
f.GetGadgetState?f.GetGadgetState():0};window.spider_GetGadgetText=function(d){var f;return(f=spider.gadget.objects.Get(d))&&f.GetGadgetText?f.GetGadgetText():""};window.spider_HideGadget=function(d,f){var g;(g=spider.gadget.objects.Get(d))&&$(g.div).css("visibility",f?"hidden":"visible")};window.spider_HyperLinkGadget=function(d,f,g,k,n,m,b,e){"undefined"===typeof e&&(e=0);var c=spider.gadget.objects.Allocate(d),h=document.createElement("a");h.innerHTML=m;h.href="";h.style.color=spider_helper_ColorToHtml(b);
0===(e&1)&&$(h).css("text-decoration","none");$(h).on("click",function(a){a.preventDefault();a.stopPropagation();q(c,0)});var a=document.createElement("div"),l=document.createElement("span");l.className="sbVerticalCenter";a.appendChild(l);l.appendChild(h);c.GetGadgetText=function(){return h.innerHTML};c.SetGadgetText=function(a){h.innerHTML=a};c.GetRequiredSize=function(){var b=$(a).css("fontSize")+" "+$(a).css("fontFamily"),b=x(c,b,c.GetGadgetText());b.width+=16;b.height+=8;return b};c.ResizeGadget=
function(c,b,d,e){s(a,c,b,d,e);$(l).width(d);$(l).height(e)};spider.gadget.register(c,10,a,h);c.ResizeGadget(f,g,k,n);return c.resultId};window.spider_ImageGadget=function(d,f,g,k,n,m,b){"undefined"===typeof b&&(b=0);var e=spider.gadget.objects.Allocate(d),c=document.createElement("div"),h=document.createElement("div");h.className=spider.image.GetCSS(m);e.image=m;put(c,h);b&2&&$(c).addClass("sbImageBorder");$(c).on({click:function(){q(e,0)},dblclick:function(){q(e,2)},contextmenu:function(a){q(e,
1);return!1}});e.GetGadgetState=function(){return e.image};e.SetGadgetState=function(a){h.className=spider.image.GetCSS(a);e.image=a};e.ResizeGadget=function(a,b,d,e){var f=u(c);s(c,a,b,d-f.x,e-f.y)};spider.gadget.register(e,9,c,c);e.ResizeGadget(f,g,k,n);return e.resultId};window.spider_IsGadget=function(d){return spider.gadget.objects.Is(d)};window.spider_ListIconGadget=function(d,f,g,k,n,m,b,e){function c(a,c){for(var b=a;b<=c;b++)p.notify(p.get(b),b)}function h(){for(var a=0;a<w.length;a++)w[a].field=
""+a,w[a].index=a;t.set("columns",w);t.resize()}"undefined"===typeof e&&(e=0);var a=spider.gadget.objects.Allocate(d),l=spider_NewList(function(){return{id:null,text:null}}),p=new spider.StoreObservable(new spider.StoreMemory),r=e,t,w=[],y=document.createElement("div"),C="single";d=spider.DojoBaseDeclare([spider.DGridOnDemandGrid,spider.DGridKeyboard,spider.DGridSelection,spider.DGridColumnResizer]);e&2&&(C="extended");t=new d({showHeader:!0,store:p,selectionMode:C});y.appendChild(t.domNode);$(y).on({click:function(){q(a,
0)},dblclick:function(){q(a,2)},contextmenu:function(c){q(a,1);return!1}});a.DisableGadget=function(c){a.isDisabled=c;t.set("allowTextSelection",c?!1:!0);t.set("selectionMode",c?"none":C)};a.AddGadgetItem=function(b,d,e,f){-1==b&&(b=spider_ListSize(l));0>=b?spider_ResetList(l):spider_SelectElement(l,b-1);b=spider_AddElement(l);b.text=d;r&1&&(b.checkBox=new dijit.form.CheckBox({onClick:function(){q(a,9)}}));e&&(b.image=e);d=spider_ListIndex(l);p.add({text:"",id:spider_ListSize(l)-1});c(d,spider_ListSize(l)-
1)};a.RemoveGadgetItem=function(b){var d=spider_ListSize(l);if(d>b&&0<=b){var e=a.GetGadgetState();e>b&&a.SetGadgetState(e-1);spider_SelectElement(l,b);spider_DeleteElement(l);p.remove(d-1);c(b,d-2)}};a.ClearGadgetItems=function(){for(var c=spider_ListSize(l),b=0;b<c;b++)a.RemoveGadgetItem(0)};a.CountGadgetItems=function(){return spider_ListSize(l)};a.AddGadgetColumn=function(a,c,b){w.splice(a,0,{field:"",index:0,label:c,width:b,sortable:!1,renderCell:function(a,c,b,d){c=spider_SelectElement(l,a.id);
a=put("div");0===this.index&&(c.checkBox&&(b=put("div"),$(b).css("float","left"),$(b).css("padding-right","8px"),put(b,c.checkBox.domNode),a.appendChild(b)),c.image&&(b=put("div"),$(b).css("float","left"),$(b).css("padding-right","8px"),b.className=spider.image.GetCSS(c.image),a.appendChild(b)));c=put("div",spider_StringField(c.text,this.index+1,spider_Chr(10)));$(c).css("white-space","nowrap");a.appendChild(c);return a}});h()};a.RemoveGadgetColumn=function(a){w.splice(a,1);h()};a.GetGadgetState=
function(){var a=-1,c;for(c in t.selection){a=c;break}return+a};a.SetGadgetState=function(a){t.clearSelection();t.select(a)};a.GetGadgetText=function(){var c=a.GetGadgetState();return-1!=c?spider_SelectElement(l,c).text:""};a.SetGadgetText=function(c){var b;for(spider_ResetList(l);b=spider_NextElement(l);)if(b.text==c){a.SetGadgetState(spider_ListIndex(l));break}};a.GetGadgetItemAttribute=function(a,c,b){return 1==c?w[b].width:0};a.SetGadgetItemAttribute=function(a,c,b,d){1==c&&(w[d].width=b,h())};
a.GetGadgetItemState=function(a){var c=0,b=spider_SelectElement(l,a);b.checkBox&&b.checkBox.get("checked")&&(c|=2);t.isSelected(a)&&(c|=1);return c};a.SetGadgetItemState=function(a,c){var b=spider_SelectElement(l,a);b.checkBox&&b.checkBox.set("checked",c&2?!0:!1);c&1?t.select(a):t.deselect(a)};a.GetGadgetItemData=function(a){var c;return(c=spider_SelectElement(l,a))?c.data?c.data:0:0};a.SetGadgetItemData=function(a,c){var b;if(b=spider_SelectElement(l,a))b.data=c};a.GetGadgetItemText=function(a,c){var b;
return(b=spider_SelectElement(l,a))?-1!=c?spider_StringField(b.text,c+1,spider_Chr(10)):b.text:""};a.SetGadgetItemText=function(a,c,b){var d;if(d=spider_SelectElement(l,a)){if(-1!=b){var e=d.text.split(spider_Chr(10));e[b]=c;d.text=e.join(spider_Chr(10))}else d.text=c;p.notify(p.get(a),a)}};a.GetGadgetColor=function(c){switch(c){case 2:return a.backColor?a.backColor:-1;case 1:return a.frontColor?a.frontColor:-1}return-1};a.SetGadgetColor=function(c,b){switch(c){case 2:$(y).css("background-color",
spider_helper_ColorToHtml(b));a.backColor=b;break;case 1:$(y).css("color",spider_helper_ColorToHtml(b)),a.frontColor=b}};a.ResizeGadget=function(a,c,b,d){s(y,a,c,b,d);a=u(t.domNode);v(t,0,0,b-a.x,d-a.y)};a.AddGadgetColumn(0,m,b);spider.gadget.register(a,12,y,t);a.ResizeGadget(f,g,k,n);var K=setInterval(function(){$(y).is(":visible")&&(clearInterval(K),t.startup(),t.resize())},10);return a.resultId};window.spider_ListViewGadget=function(d,f,g,k,n,m){function b(){a=spider_NewList(function(){return{id:null,
text:null}});l=new spider.StoreObservable(new spider.StoreMemory);p.setStore(l)}function e(a,c){for(var b=a;b<=c;b++)l.notify(l.get(b),b)}"undefined"===typeof m&&(m=0);var c=spider.gadget.objects.Allocate(d),h="single",a,l,p,r=document.createElement("div");d=spider.DojoBaseDeclare([spider.DGridOnDemandGrid,spider.DGridKeyboard,spider.DGridSelection]);m&1?h="extended":m&2&&(h="toggle");p=new d({showHeader:!1,selectionMode:h,columns:{text:""},renderRow:function(c,b){var d=spider_SelectElement(a,c.id),
d=put("div",d.text);$(d).css("padding","2px");return d}});b();r.appendChild(p.domNode);$(r).on({click:function(){q(c,0)},dblclick:function(){q(c,2)},contextmenu:function(a){q(c,1);return!1}});c.DisableGadget=function(a){c.isDisabled=a;p.set("allowTextSelection",a?!1:!0);p.set("selectionMode",a?"none":h)};c.AddGadgetItem=function(c,b,d,f){-1==c&&(c=spider_ListSize(a));0>=c?spider_ResetList(a):spider_SelectElement(a,c-1);spider_AddElement(a).text=b;c=spider_ListIndex(a);l.add({text:"",id:spider_ListSize(a)-
1});e(c,spider_ListSize(a)-1)};c.RemoveGadgetItem=function(b){var d=spider_ListSize(a);if(d>b&&0<=b){var f=c.GetGadgetState();f>b&&c.SetGadgetState(f-1);spider_SelectElement(a,b);spider_DeleteElement(a);l.remove(d-1);e(b,d-2)}};c.ClearGadgetItems=function(){b()};c.CountGadgetItems=function(){return spider_ListSize(a)};c.GetGadgetState=function(){var a=-1,c;for(c in p.selection){a=c;break}return+a};c.SetGadgetState=function(a){p.clearSelection();p.select(a)};c.GetGadgetText=function(){var b=c.GetGadgetState();
return-1!=b?spider_SelectElement(a,b).text:""};c.SetGadgetText=function(b){var d;for(spider_ResetList(a);d=spider_NextElement(a);)if(d.text==b){c.SetGadgetState(spider_ListIndex(a));break}};c.GetGadgetItemState=function(a){return p.isSelected(a)?1:0};c.SetGadgetItemState=function(a,c){c?p.select(a):p.deselect(a)};c.GetGadgetItemData=function(c){var b;return(b=spider_SelectElement(a,c))?b.data?b.data:0:0};c.SetGadgetItemData=function(c,b){var d;if(d=spider_SelectElement(a,c))d.data=b};c.GetGadgetItemText=
function(c,b){var d;return(d=spider_SelectElement(a,c))?d.text:""};c.SetGadgetItemText=function(c,b,d){if(d=spider_SelectElement(a,c))d.text=b,l.notify(l.get(c),c)};c.GetGadgetColor=function(a){switch(a){case 2:return c.backColor?c.backColor:-1;case 1:return c.frontColor?c.frontColor:-1}return-1};c.SetGadgetColor=function(a,b){switch(a){case 2:$(r).css("background-color",spider_helper_ColorToHtml(b));c.backColor=b;break;case 1:$(r).css("color",spider_helper_ColorToHtml(b)),c.frontColor=b}};c.ResizeGadget=
function(a,c,b,d){s(r,a,c,b,d);a=u(p.domNode);v(p,0,0,b-a.x,d-a.y)};$(r).find("div").each(function(){if("dgrid-scroller"==$(this).attr("class"))return $(this).css("margin-top","0px"),!1});spider.gadget.register(c,6,r,p);c.ResizeGadget(f,g,k,n);return c.resultId};window.spider_OpenGadgetList=function(d,f){var g,k;if(g=spider.gadget.objects.Get(d)){switch(g.type){case 16:k=g.contentPane.domNode;break;case 11:k=g.gadget.domNode;break;case 28:if(g=g.getPanelChild(f))k=g.domNode}k&&spider.window.gadgetList.push(k)}};
window.spider_OptionGadget=function(d,f,g,k,n,m){var b=spider.gadget.objects.Allocate(d);d="spideroption_"+b.id;5!=spider.gadget.lastType&&spider.gadget.optionGroupCount++;var e=new dijit.form.RadioButton({id:d,name:"spideroptiongroup"+spider.gadget.optionGroupCount,onClick:function(){q(b,0)}}),c=document.createElement("div"),h=document.createElement("span");h.className="sbVerticalCenter";c.appendChild(h);h.appendChild(e.domNode);var a=put(h,"label",{htmlFor:d,innerHTML:m});$(a).css("padding-left",
"5px");b.DisableGadget=function(c){$(a).css("color",c?"gray":"");e.set("disabled",c?!0:!1)};b.GetGadgetState=function(){return e.get("checked")?1:0};b.SetGadgetState=function(a){e.set("checked",a)};b.GetGadgetText=function(){return a.innerHTML};b.SetGadgetText=function(c){a.innerHTML=c};b.GetRequiredSize=function(){var a=$(c).css("fontSize")+" "+$(c).css("fontFamily"),a=x(b,a,b.GetGadgetText());a.width+=28;a.height+=6;return a};b.ResizeGadget=function(a,b,d,e){s(c,a,b,d,e);$(h).width(d);$(h).height(e)};
spider.gadget.register(b,5,c,e);b.ResizeGadget(f,g,k,n);return b.resultId};window.spider_PanelGadget=function(d,f,g,k,n){function m(a){var c=e.getChildren();return 0<=a&&a<c.length?c[a]:null}var b=spider.gadget.objects.Allocate(d),e=new dijit.layout.TabContainer({doLayout:!0}),c=document.createElement("div");c.appendChild(e.domNode);e.watch("selectedChildWidget",function(a,c,d){q(b,9)});var h=function(){$(c).find("div").each(function(){if("dijitTabListWrapper"==spider_Left($(this).attr("class"),19))return-2==
$(this).cssValue("left")&&($(this).css("left","0px"),$(this).css("top","1px")),!1})};b.getPanelChild=m;b.AddGadgetItem=function(a,c,b,d){a=new dijit.layout.ContentPane({title:c,iconClass:b?spider.image.GetCSS(b):null});e.addChild(a);spider.window.gadgetList.set(a.domNode);e.startup();e.resize();h()};b.GetGadgetState=function(){for(var a=e.getChildren(),c=0;c<a.length;c++)if(a[c].get("selected"))return c;return-1};b.SetGadgetState=function(a){var c;(c=m(a))&&e.selectChild(c)};b.GetGadgetItemData=function(a){var c;
return(c=m(a))&&c.spiderData?c.spiderData:0};b.SetGadgetItemData=function(a,c){var b;if(b=m(a))b.spiderData=c};b.GetGadgetItemText=function(a,c){var b;return(b=m(a))?b.get("title"):""};b.SetGadgetItemText=function(a,c,b){var d;(d=m(a))&&d.set("title",c)};b.SetGadgetItemImage=function(a,c){var b;(b=m(a))&&b.set("iconClass",c?spider.image.GetCSS(c):null)};b.GetGadgetAttribute=function(a){var b;if(b=m(0))switch(a){case 1:return $(b.domNode).width();case 2:return $(b.domNode).height();case 3:return $(c).height()-
$(b.domNode).height()}return 0};b.ResizeGadget=function(a,d,f,g){s(c,a,d,f,g);v(e,0,0,f,g);b.disableResize||e.resize();h()};spider.gadget.register(b,28,c,e);b.disableResize=!0;b.ResizeGadget(f,g,k,n);b.disableResize=!1;spider.window.gadgetList.push(null);return b.resultId};window.spider_ProgressBarGadget=function(d,f,g,k,n,m,b,e){function c(){a.maximum=h.maximum-h.minimum}"undefined"===typeof e&&(e=0);var h=spider.gadget.objects.Allocate(d),a=new dijit.ProgressBar;$(a.labelNode).css("visibility",
"hidden");$(a.internalProgress).css("height","100%");var l=document.createElement("div");l.appendChild(a.domNode);h.minimum=m;h.maximum=b;c();h.GetGadgetState=function(){return a.get("value")+h.minimum};h.SetGadgetState=function(c){a.set("value",c-h.minimum)};h.GetGadgetAttribute=function(a){switch(a){case 1:return h.minimum;case 2:return h.maximum}return 0};h.SetGadgetAttribute=function(a,b){switch(a){case 1:h.minimum=b;c();break;case 2:h.maximum=b,c()}};h.ResizeGadget=function(c,b,d,e){s(l,c,b,
d,e);c=u(a.domNode);v(a,0,0,d-c.x,e-c.y)};spider.gadget.register(h,14,l,l);h.ResizeGadget(f,g,k,n);return h.resultId};window.spider_RemoveGadgetColumn=function(d,f){var g;(g=spider.gadget.objects.Get(d))&&g.RemoveGadgetColumn&&g.RemoveGadgetColumn(f)};window.spider_RemoveGadgetItem=function(d,f){var g;(g=spider.gadget.objects.Get(d))&&g.RemoveGadgetItem&&g.RemoveGadgetItem(f)};window.spider_ResizeGadget=function(d,f,g,k,n){var m;if(m=spider.gadget.objects.Get(d))-65535==f&&(f=I(d)),-65535==g&&(g=
J(d)),-65535==k&&(k=H(d)),-65535==n&&(n=G(d)),m.ResizeGadget&&m.ResizeGadget(f|0,g|0,k|0,n|0)};window.spider_ScrollAreaGadget=function(d,f,g,k,n,m,b,e,c){"undefined"===typeof e&&(e=1);"undefined"===typeof c&&(c=0);d=spider.gadget.objects.Allocate(d);var h=new dijit.layout.ContentPane({style:"overflow: hidden; padding: 0px;"}),a=document.createElement("div");$(a).css("overflow","auto");c&8||$(a).addClass("sbScrollAreaBorder");h.placeAt(a);v(h,0,0,m,b);d.GetGadgetAttribute=function(c){switch(c){case 1:return $(h.domNode).width();
case 2:return $(h.domNode).height();case 3:return a.scrollLeft;case 4:return a.scrollTop;case 5:return 1}return 0};d.SetGadgetAttribute=function(c,b){switch(c){case 1:$(h.domNode).width(b);break;case 2:$(h.domNode).height(b);break;case 3:a.scrollLeft=b;break;case 4:a.scrollTop=b}};d.ResizeGadget=function(c,b,d,e){var f=u(a);s(a,c,b,d-f.x,e-f.y)};spider.gadget.register(d,16,a,a);d.ResizeGadget(f,g,k,n);spider.window.gadgetList.push(h.domNode);d.contentPane=h;return d.resultId};window.spider_SetActiveGadget=
function(d){var f;(f=spider.gadget.objects.Get(d))&&f.SetActiveGadget&&f.SetActiveGadget()};window.spider_SetGadgetAttribute=function(d,f,g){var k;(k=spider.gadget.objects.Get(d))&&k.SetGadgetAttribute&&k.SetGadgetAttribute(f,g)};window.spider_SetGadgetColor=function(d,f,g){var k;(k=spider.gadget.objects.Get(d))&&k.SetGadgetColor&&k.SetGadgetColor(f,g)};window.spider_SetGadgetData=function(d,f){var g;if(g=spider.gadget.objects.Get(d))g.userData=f};window.spider_SetGadgetFont=function(d,f){var g;if(g=
spider.gadget.objects.Get(d))g.SetGadgetFont?g.SetGadgetFont(f):($(g.div).css("fontFamily",f.family),$(g.div).css("fontSize",f.size))};window.spider_SetGadgetItemAttribute=function(d,f,g,k,n){"undefined"===typeof n&&(n=-1);var m;(m=spider.gadget.objects.Get(d))&&m.SetGadgetItemAttribute&&m.SetGadgetItemAttribute(f,g,k,n)};window.spider_SetGadgetItemData=function(d,f,g){var k;(k=spider.gadget.objects.Get(d))&&k.SetGadgetItemData&&k.SetGadgetItemData(f,g)};window.spider_SetGadgetItemImage=function(d,
f,g){var k;(k=spider.gadget.objects.Get(d))&&k.SetGadgetItemImage&&k.SetGadgetItemImage(f,g)};window.spider_SetGadgetItemState=function(d,f,g){var k;(k=spider.gadget.objects.Get(d))&&k.SetGadgetItemState&&k.SetGadgetItemState(f,g)};window.spider_SetGadgetItemText=function(d,f,g,k){"undefined"===typeof k&&(k=-1);var n;(n=spider.gadget.objects.Get(d))&&n.SetGadgetItemText&&n.SetGadgetItemText(f,g,k)};window.spider_SetGadgetState=function(d,f){var g;if(g=spider.gadget.objects.Get(d))E(g),g.SetGadgetState&&
g.SetGadgetState(f),F(g)};window.spider_SetGadgetText=function(d,f){var g;if(g=spider.gadget.objects.Get(d))E(g),g.SetGadgetText&&g.SetGadgetText(f),F(g)};window.spider_SpinGadget=function(d,f,g,k,n,m,b,e){"undefined"===typeof e&&(e=0);var c=spider.gadget.objects.Allocate(d),h=new dijit.form.NumberSpinner({constraints:{min:m,max:b},intermediateChanges:!0,onChange:function(){var a=h.get("value");a>c.oldValue?q(c,4):a<c.oldValue&&q(c,5);c.oldValue=a;q(c,9)},onFocus:function(){q(c,7)},onBlur:function(){q(c,
8)}}),a=z(h.upArrowNode,"div","dijitArrowButtonInner"),l=z(h.downArrowNode,"div","dijitArrowButtonInner");"flat"===spider.gadgetTheme&&($(a).css("position","absolute"),$(l).css("position","absolute"));e&1&&$(h.focusNode).attr("disabled",!0);var p=document.createElement("div");p.appendChild(h.domNode);c.DisableGadget=function(a){B(c,h.focusNode.parentNode,h.focusNode,a)};c.GetGadgetState=function(){return h.get("value")};c.SetGadgetState=function(a){c.oldValue=a;h.set("value",a)};c.GetGadgetAttribute=
function(a){switch(a){case 1:return h.attr("constraints").min;case 2:return h.attr("constraints").max}return 0};c.SetGadgetAttribute=function(a,c){var b=h.attr("constraints");switch(a){case 1:b.min=c;h.attr("constraints",b);break;case 2:b.max=c,h.attr("constraints",b)}};c.GetGadgetColor=function(a){switch(a){case 2:return c.backColor?c.backColor:-1;case 1:return c.frontColor?c.frontColor:-1}return-1};c.SetGadgetColor=function(a,b){A(c,h.focusNode.parentNode,h.focusNode,a,b)};c.GetRequiredSize=function(){var a=
$(p).css("fontSize")+" "+$(p).css("fontFamily"),a=x(c,a,"Hg");a.width=60;a.height+=5;return a};c.ResizeGadget=function(c,b,d,e){s(p,c,b,d,e);c=u(h.domNode);v(h,0,0,d-c.x,e-c.y);d=z(p,"div","dijitSpinnerButtonContainer");$(d).height(e-c.y);$(a).css("top",(e-c.y)/4-8);$(l).css("top",(e-c.y)/4-8);"claro"==spider.gadgetTheme?$(h.focusNode).height(e-c.y-2):$(h.focusNode).height(e-c.y)};c.SetGadgetState(m);spider.gadget.register(c,2,p,h);c.ResizeGadget(f,g,k,n);return c.resultId};window.spider_SplitterGadget=
function(d,f,g,k,n,m,b,e){"undefined"===typeof e&&(e=0);var c,h,a,l,p,r=spider.gadget.objects.Allocate(d),t=function(b){c.ResizeGadget(0,0,$(a.domNode).width(),$(a.domNode).height());h.ResizeGadget(0,0,$(l.domNode).width(),$(l.domNode).height())};if((c=spider.gadget.objects.Get(m))&&(h=spider.gadget.objects.Get(b))){p=new dijit.layout.BorderContainer({design:"sidebar",gutters:!1,liveSplitters:!0});a=new dijit.layout.ContentPane({region:e&1?"left":"top",style:"overflow: hidden",content:"",splitter:!0});
p.addChild(a);a.domNode.appendChild(c.div);l=new dijit.layout.ContentPane({style:"overflow: hidden",region:"center",content:"",splitter:!0});p.addChild(l);l.domNode.appendChild(h.div);var w=document.createElement("div");p.placeAt(w);r.GetGadgetState=function(){return e&1?$(a.domNode).width():$(a.domNode).height()};r.SetGadgetState=function(c){e&1?$(a.domNode).width(c):$(a.domNode).height(c);p.resize();t()};r.GetGadgetAttribute=function(b){switch(b){case 3:return c.id;case 4:return h.id;case 1:return a.attr("minSize");
case 2:if(r.secondMinimumSize)return r.secondMinimumSize}return 0};r.SetGadgetAttribute=function(b,d){var e;switch(b){case 3:if(e=spider.gadget.objects.Get(d))spider_WindowID(c.windowId).content.appendChild(c.div),c=e,a.domNode.appendChild(c.div),t();break;case 4:if(e=spider.gadget.objects.Get(d))spider_WindowID(h.windowId).content.appendChild(h.div),h=e,l.domNode.appendChild(h.div),t();break;case 1:a.attr("minSize",d);break;case 2:r.secondMinimumSize=d,r.secondMinimumSize&&a.attr("maxSize",$(p.domNode).width()-
r.secondMinimumSize-16)}};r.ResizeGadget=function(a,c,b,d){s(w,a,c,b,d);v(p,0,0,b,d);p.resize();t()};spider.DojoAspect.after(a,"resize",function(b,d){c.ResizeGadget(0,0,$(a.domNode).width(),$(a.domNode).height())});spider.DojoAspect.after(l,"resize",function(a,c){h.ResizeGadget(0,0,$(l.domNode).width(),$(l.domNode).height())});spider.gadget.register(r,29,w,p);p.startup();r.ResizeGadget(f,g,k,n);e&1?r.SetGadgetState(k/2-5):r.SetGadgetState(n/2-5)}else r.resultId=0;return r.resultId};window.spider_StringGadget=
function(d,f,g,k,n,m,b){"undefined"===typeof b&&(b=0);var e=spider.gadget.objects.Allocate(d),c;c=b&4?new dijit.form.NumberTextBox({constraints:{min:0,places:0}}):new dijit.form.TextBox({type:b&1?"password":"text"});c.intermediateChanges=!0;c.attr("onChange",function(){b&16&&c.set("value",c.get("value").toUpperCase());b&8&&c.set("value",c.get("value").toLowerCase());q(e,9)});c.attr("onFocus",function(){q(e,7)});c.attr("onBlur",function(){q(e,8)});b&2&&c.attr("readOnly",!0);b&32&&$(c.domNode).css("border",
"0px");var h=document.createElement("div");h.appendChild(c.domNode);e.DisableGadget=function(a){B(e,c.focusNode.parentNode,c.focusNode,a)};e.SetActiveGadget=function(){require(["dijit/focus"],function(a){a.focus(c.focusNode)})};e.GetGadgetText=function(){return c.get("value")};e.SetGadgetText=function(a){c.set("value",a)};e.GetGadgetAttribute=function(a){return 1==a?c.get("maxlength"):0};e.SetGadgetAttribute=function(a,b){1==a&&(c.set("maxlength",b),c.set("value",c.get("value").substring(0,b)))};
e.GetGadgetColor=function(a){switch(a){case 2:return e.backColor?e.backColor:-1;case 1:return e.frontColor?e.frontColor:-1}return-1};e.SetGadgetColor=function(a,b){A(e,c.focusNode.parentNode,c.focusNode,a,b)};e.GetRequiredSize=function(){var a=$(h).css("fontSize")+" "+$(h).css("fontFamily"),a=x(e,a,"Hg");a.width=30;a.height+=10;return a};e.ResizeGadget=function(a,b,d,e){s(h,a,b,d,e);a=u(c.domNode);v(c,0,0,d-a.x,e-a.y);"claro"==spider.gadgetTheme?$(c.focusNode).height(e-a.y-2):$(c.focusNode).height(e-
a.y)};c.set("value",m);spider.gadget.register(e,2,h,c);e.ResizeGadget(f,g,k,n);return e.resultId};window.spider_TextGadget=function(d,f,g,k,n,m,b){"undefined"===typeof b&&(b=0);var e=spider.gadget.objects.Allocate(d),c=document.createElement("div"),h=document.createElement("span");h.className="sbVerticalCenter";c.appendChild(h);h.innerHTML=m;b&4&&$(c).addClass("sbTextBorder");b&2?$(c).css("text-align","right"):b&1&&$(c).css("text-align","center");e.GetGadgetText=function(){return h.innerHTML};e.SetGadgetText=
function(a){h.innerHTML=a};e.GetGadgetColor=function(a){switch(a){case 2:return e.backColor?e.backColor:-1;case 1:return e.frontColor?e.frontColor:-1}return-1};e.SetGadgetColor=function(a,b){switch(a){case 2:$(c).css("background-color",spider_helper_ColorToHtml(b));e.backColor=b;break;case 1:$(c).css("color",spider_helper_ColorToHtml(b)),e.frontColor=b}};e.GetRequiredSize=function(){var a=$(c).css("fontSize")+" "+$(c).css("fontFamily"),a=x(e,a,e.GetGadgetText());a.width+=8;a.height+=6;return a};e.ResizeGadget=
function(a,b,d,e){var f=u(c);s(c,a,b,d-f.x,e-f.y);$(h).width(d-f.x);$(h).height(e-f.y)};spider.gadget.register(e,3,c,h);e.ResizeGadget(f,g,k,n);return e.resultId};window.spider_TrackBarGadget=function(d,f,g,k,n,m,b,e){"undefined"===typeof e&&(e=0);var c=spider.gadget.objects.Allocate(d),h=new (e&2?dijit.form.VerticalSlider:dijit.form.HorizontalSlider)({minimum:m,maximum:b,showButtons:!1,intermediateChanges:!0,discreteValues:b-m+1,onChange:function(a){q(c,0)}}),a=document.createElement("div");a.appendChild(h.domNode);
c.GetGadgetState=function(){return h.get("value")|0};c.SetGadgetState=function(a){h.set("value",a)};c.GetGadgetAttribute=function(a){switch(a){case 1:return h.get("minimum");case 2:return h.get("maximum")}return 0};c.SetGadgetAttribute=function(a,c){switch(a){case 1:h.set("minimum",c);break;case 2:h.set("maximum",c)}};c.GetRequiredSize=function(){var c={width:0,height:0};$.each($(a).children(),function(a,b){c.width+=$(b).outerWidth(!0);c.height+=$(b).outerHeight(!0)});return c};c.ResizeGadget=function(c,
b,d,e){s(a,c,b,d,e);v(h,0,0,d,e)};spider.gadget.register(c,17,a,h);c.ResizeGadget(f,g,k,n);return c.resultId};window.spider_TreeGadget=function(d,f,g,k,n,m){"undefined"===typeof m&&(m=0);var b=spider.gadget.objects.Allocate(d),e=spider_NewList(function(){return{id:null,text:null}}),c,h=0,a=!1,l,p=document.createElement("div");$(p).addClass("sbTreeBorder");spider.DojoBaseLang.extend(dijit.Tree,{refreshModel:function(){this._itemNodesMap={};this.rootNode.state="UNCHECKED";this.model.root.children=null;
this.rootNode&&this.rootNode.destroyRecursive();this._load()}});c=new spider.CBTreeStoreHierarchy;d=new spider.CBTreeModelForestStoreModel({store:c,query:{type:"root"},rootLabel:""});l=new dijit.Tree({model:d,getIconClass:function(a,c){var b;return(b=a.spiderItem)&&b.image?spider.image.GetCSS(b.image):""},showRoot:!1,onClick:function(a){q(b,0);q(b,9)},onDblClick:function(a){q(b,2)}});$(p).on("contextmenu",function(a){q(b,1);return!1});p.appendChild(l.domNode);var r=function(){a||(a=setInterval(function(){clearInterval(a);
a=!1;l.refreshModel()},0))};b.AddGadgetItem=function(a,b,d,f){-1==a&&(a=spider_ListSize(e));0>=a?spider_ResetList(e):spider_SelectElement(e,a-1);a=spider_AddElement(e);a.id=h;a.text=b;a.subLevel=f;d&&(a.image=d);d="";var g;spider_ListIndex(e);if(0<f)for(;g=spider_PreviousElement(e);)if(g.subLevel<f){d=g.id;break}c.add({id:h,name:b,type:0===f?"root":"child",parent:[d],spiderItem:a});h++;r()};b.RemoveGadgetItem=function(a){spider_ListSize(e)>a&&0<=a&&(a=spider_SelectElement(e,a),spider_DeleteElement(e),
c.remove(a.id),l.set("selectedItems",[]),r())};b.ClearGadgetItems=function(){for(var a=spider_ListSize(e),c=0;c<a;c++)b.RemoveGadgetItem(0)};b.CountGadgetItems=function(){return spider_ListSize(e)};b.GetGadgetState=function(){var a=-1,c,b;if(c=l.attr("selectedItem"))for(spider_ResetList(e);b=spider_NextElement(e);)if(b.id==c.id){a=spider_ListIndex(e);break}return a};b.SetGadgetState=function(a){var b;(b=spider_SelectElement(e,a))&&l.set("selectedItems",[c.get(b.id)])};b.GetGadgetText=function(){var a=
b.GetGadgetState();return-1!=a?spider_SelectElement(e,a).text:""};b.SetGadgetText=function(a){var c;for(spider_ResetList(e);c=spider_NextElement(e);)if(c.text==a){b.SetGadgetState(spider_ListIndex(e));break}};b.GetGadgetItemState=function(a){var b=0;if(a=spider_SelectElement(e,a)){var d=l.get("selectedItem");d&&d.id==a.id&&(b|=1);a=l.getNodesByItem(c.get(a.id));b=a[0].isExpanded?b|2:b|8}return b};b.SetGadgetItemState=function(b,d){var f;if(f=spider_SelectElement(e,b))switch(a&&(clearInterval(a),a=
!1,l.refreshModel()),d){case 1:l.set("selectedItems",[c.get(f.id)]);break;case 2:f=l.getNodesByItem(c.get(f.id));l._expandNode(f[0]);break;case 8:f=l.getNodesByItem(c.get(f.id)),l._collapseNode(f[0])}};b.GetGadgetItemData=function(a){var b;return(b=spider_SelectElement(e,a))?b.data?b.data:0:0};b.SetGadgetItemData=function(a,b){var c;if(c=spider_SelectElement(e,a))c.data=b};b.GetGadgetItemText=function(a,b){var c;return(c=spider_SelectElement(e,a))?c.text:""};b.SetGadgetItemText=function(a,b,c){if(a=
spider_SelectElement(e,a))a.text=b,r()};b.GetGadgetColor=function(a){switch(a){case 2:return b.backColor?b.backColor:-1;case 1:return b.frontColor?b.frontColor:-1}return-1};b.SetGadgetColor=function(a,c){switch(a){case 2:$(p).css("background-color",spider_helper_ColorToHtml(c));b.backColor=c;break;case 1:$(p).css("color",spider_helper_ColorToHtml(c)),b.frontColor=c}};b.ResizeGadget=function(a,b,c,d){var e=u(p);s(p,a,b,c-e.x,d-e.y);v(l,0,0,c-e.x,d-e.y)};spider.gadget.register(b,27,p,l);b.ResizeGadget(f,
g,k,n);l.startup();return b.resultId};window.spider_UnbindGadgetEvent=function(d,f,g){"undefined"===typeof g&&(g=-1);var k;(k=spider.gadget.objects.Get(d))&&spider_UnbindEvent(1,f,k.windowId,k.id,g)};window.spider_UseGadgetList=function(d){var f=spider.window.gadgetList.get();spider.window.gadgetList.set(d.content);return f};window.spider_WebGadget=function(d,f,g,k,n,m,b){"undefined"===typeof b&&(b=0);var e=spider.gadget.objects.Allocate(d),c=document.createElement("div");$(c).addClass("sbWebBorder");
var h=document.createElement("iframe");$(h).load(function(){q(e,6)});h.src=m;h.setAttribute("frameborder",0);c.appendChild(h);e.GetGadgetText=function(){return h.src};e.SetGadgetText=function(a){h.src=a};e.GetGadgetItemText=function(a,b){try{switch(a){case 1:return $(h).contents().find("html").html();case 4:var c;var d=h.contentWindow.document;c=d.getSelection?d.getSelection():d.selection?d.selection.createRange().text:void 0;return c;case 2:return $(h).contents().find("title").html()}}catch(e){}return""};
e.ResizeGadget=function(a,b,d,e){var f=u(c);s(c,a,b,d-f.x,e-f.y);s(h,0,0,d-f.x,e-f.y)};spider.gadget.register(e,18,c,h);e.ResizeGadget(f,g,k,n);return e.resultId};window.spider_gadget_GetRequiredSize=function(d){var f;spider.gadget.context||(spider.gadget.canvas=document.createElement("canvas"),spider.gadget.canvas.width=2E3,spider.gadget.canvas.height=200,spider.gadget.context=spider.gadget.canvas.getContext("2d"));return(f=spider.gadget.objects.Get(d))&&f.GetRequiredSize?f.GetRequiredSize():{width:0,
height:0}}})();

(function(){function v(a){var b;if(-1==a)spider.window.a.CleanAll();else if(b=spider.window.a.Get(a))b.id==spider.window.b&&(spider.window.b=-1),b.n&&b.n(),b.window.parentNode.removeChild(b.window),spider.window.a.Remove(a)}function s(a){if(a=spider.window.a.Get(a))a.c&4096?spider.window.b=a.id:a.element.style.zIndex!=spider.window.j&&(a.o?(a.element.style.zIndex=spider.window.k,spider.window.k++):(a.element.style.zIndex=spider.window.j,spider.window.j++),spider.window.b=a.id)}function n(a){return a.c&
4608?0:$(a.contentFrame).cssValue("marginRight")+$(a.contentFrame).cssValue("marginLeft")+$(a.contentFrame).cssValue("borderRightWidth")+$(a.contentFrame).cssValue("borderLeftWidth")}function k(a){return a.c&4608?0:$(a.contentFrame).cssValue("marginTop")+$(a.contentFrame).cssValue("marginBottom")+$(a.contentFrame).cssValue("borderTopWidth")+$(a.contentFrame).cssValue("borderBottomWidth")}function t(a,b,c,f,p){if(a=spider.window.a.Get(a))-65535!=b&&(a.element.style.left=b+"px"),-65535!=c&&(a.element.style.top=
c+"px"),-65535!=f&&$(a.element).width(f+n(a)),-65535!=p&&$(a.element).height(p+k(a))}function w(a,b){var c,f;b&1&&(c=spider_DesktopWidth(0)/2-x(a,0)/2,f=spider_DesktopHeight(0)/2-y(a,0)/2,t(a,c,f,-65535,-65535))}function x(a,b){"undefined"===typeof b&&(b=1);var c;return(c=spider.window.a.Get(a))?c.c&4608?$(c.element).width():1==b?$(c.element).width()-n(c):$(c.element).width()+2:0}function y(a,b){"undefined"===typeof b&&(b=1);var c;return(c=spider.window.a.Get(a))?c.c&4608?$(c.element).height()-$(c.content).cssValue("top"):
1==b?$(c.element).height()-k(c):$(c.element).height()-k(c)+$(c.title).height()+9:0}spider.window={a:new spider.object(v),b:-1,h:{},j:100,k:1E8,currentWindowId:-1,gadgetList:null};spider.window.m=function(){return{d:null,e:0,stack:{},init:function(a){this.d=a;this.e=0},get:function(){return this.d},set:function(a){this.d=a},push:function(a){this.stack[this.e]=this.d;this.e++;this.d=a},pop:function(){this.e--;this.d=this.stack[this.e]}}};spider.window.gadgetList=new spider.window.m;window.spider_InitWindow=
function(){};window.spider_CloseWindow=v;window.spider_OpenWindow=function(a,b,c,f,p,e,g,q){"undefined"===typeof g&&(g=16);"undefined"===typeof q&&(q=null);var d=spider.window.a.Allocate(a);d.f=-1;d.g=-1;d.l=0;a=document.getElementById("spiderbody");q=document.createElement("div");var h=document.createElement("div"),k=document.createElement("div"),n=document.createElement("div");g&4096?(c=b=0,f=spider_DesktopWidth(0),p=spider_DesktopHeight(0),h.style.zIndex=80,h.className="spiderwindow-background",
g&=-49,$(window).resize(function(){t(d.id,0,0,spider_DesktopWidth(0),spider_DesktopHeight(0));spider.event.Send(7,d.id,0,0)})):g&512?(h.className="spiderwindow-background",g&=-49):(h.className="spiderwindow sbNoSelect",n.innerHTML=e,n.className="spiderwindow-title",k.appendChild(n),g&16&&(e=document.createElement("div"),e.className="spiderwindow-closebutton",$(e).on("click",function(){spider.event.Send(4,d.id,0,0)}),k.appendChild(e)));var l=document.createElement("div");l.className="spiderwindow-content";
$(l).on({mouseover:function(a){var b=l.getBoundingClientRect();d.f=a.clientX-b.left|0;d.g=a.clientY-b.top|0},mouseout:function(){d.f=-1;d.g=-1},mousemove:function(a){var b=l.getBoundingClientRect();d.f=a.clientX-b.left|0;d.g=a.clientY-b.top|0}});var r=document.createElement("div");r.className="spiderwindow-menubar";var u=document.createElement("div"),m=document.createElement("div");e=document.createElement("div");d.window=q;d.element=h;d.contentFrame=l;d.content=m;d.menu=r;d.toolBar=u;d.statusBar=
e;d.title=k;d.i=n;d.c=g;$(u).on("contextmenu",function(){return!1});$(r).on("contextmenu",function(){return!1});s(d.id);q.appendChild(h);h.appendChild(k);h.appendChild(l);m.style.position="absolute";m.style.top="0px";m.style.left="0px";$(m).css("overflow","hidden");$(m).css("width","100%");$(m).css("height","100%");l.appendChild(r);l.appendChild(u);l.appendChild(m);l.appendChild(e);h.style.position="absolute";a.appendChild(q);g&32&&($(h).resizable({handles:"n, e, s, w, ne, se, sw, nw",containment:"body",
ghost:!1,resize:function(){spider.event.Send(7,d.id,0,0)}}),$(".ui-icon-gripsmall-diagonal-se").css("background-image","url('')"),g&16&&($(h).resizable("option","minWidth",80),$(h).resizable("option","minHeight",40)));g&4608||$(h).draggable({cancel:".spiderwindow-content",p:function(){spider.event.Send(6,d.id,0,0)}});$(h).on("mousedown",function(){spider.window.b!=d.id&&(-1!=spider.window.b&&spider.event.Send(16,spider.window.b,0,0),spider.event.Send(8,d.id,0,0),s(d.id))});d.AdjustContent=function(){$(m).css("top",
$(r).height()+$(u).height())};t(d.id,b,c,f,p);w(d.id,g);spider.window.gadgetList.init(m);spider.window.currentWindowId=d.id;return d.resultId};window.spider_AddWindowTimer=function(a,b,c){var f;if(f=spider.window.a.Get(a))spider.window.h[f.id+"_"+b]=setInterval(function(){spider.event.Send(12,f.id,b,0)},c)};window.spider_RemoveWindowTimer=function(a,b){var c;if(c=spider.window.a.Get(a))c=c.id+"_"+b,spider.window.h[c]&&(clearInterval(spider.window.h[c]),delete spider.window.h[c])};window.spider_HideWindow=
function(a,b){var c;if(c=spider.window.a.Get(a))c.element.style.visibility=0===b?"visible":"hidden"};window.spider_GetWindowTitle=function(a){if(a=spider.window.a.Get(a)){if(a.c&4096)return document.title;if(a.i)return a.i.innerHTML}return""};window.spider_SetWindowTitle=function(a,b){var c;if(c=spider.window.a.Get(a))c.c&4096?document.title=b:c.i&&(c.i.innerHTML=b)};window.spider_GetWindowData=function(a){var b;return(b=spider.window.a.Get(a))?b.l:0};window.spider_SetWindowData=function(a,b){var c;
if(c=spider.window.a.Get(a))c.l=b};window.spider_GetActiveWindow=function(){return spider.window.b};window.spider_SetActiveWindow=s;window.spider_StickyWindow=function(a,b){var c;if(c=spider.window.a.Get(a))c.o=b,s(c.id)};window.spider_ResizeWindow=t;window.spider_WindowBounds=function(a,b,c,f,p){var e;(e=spider.window.a.Get(a))&&e.c&32&&(-65535!=b&&$(e.element).resizable("option","minWidth",b+n(e)),-65535!=c&&$(e.element).resizable("option","minHeight",c+k(e)),-65535!=f&&$(e.element).resizable("option",
"maxWidth",f+n(e)),-65535!=p&&$(e.element).resizable("option","maxHeight",p+k(e)))};window.spider_WindowX=function(a){var b;return(b=spider.window.a.Get(a))?b.element.getBoundingClientRect().left:0};window.spider_WindowY=function(a){var b;return(b=spider.window.a.Get(a))?b.element.getBoundingClientRect().top:0};window.spider_WindowWidth=x;window.spider_WindowHeight=y;window.spider_WindowMouseX=function(a){var b;return(b=spider.window.a.Get(a))?b.f:0};window.spider_WindowMouseY=function(a){var b;return(b=
spider.window.a.Get(a))?b.g:0};window.spider_WindowID=function(a){var b;return(b=spider.window.a.Get(a))?b:null};window.spider_IsWindow=function(a){return spider.window.a.Is(a)};window.spider_window_Center=w})();

function f_closewindowevent() {
spider_CloseWindow(spider_EventWindow());
return 0;
}

//
SpiderLaunch = function() {
 spider_InitFunctions();
spider_OpenWindow(0,100,100,320,200,_S1,32);
spider_OpenWindow(1,500,100,320,200,_S2);
spider_OpenWindow(2,100,400,320,200,_S3);
spider_BindEvent(4,f_closewindowevent);

}


function spider_InitFunctions() {
spider_InitMap();
spider_Event_Init();
spider_InitImageDecoder();
spider_InitImage();
spider_Init2DDrawing();
spider_InitDesktop();
spider_InitList();
spider_InitGadget();
spider_InitWindow();
}


